import test from 'node:test';
import assert from 'node:assert/strict';
import {PDFDocument,PDFName,PDFString} from 'pdf-lib';
import {validateContent,publicProduct} from '../lib/content.mjs';
import {validateFile,documentPdf,bundlePdf,sanitizeCsv} from '../lib/files.mjs';
import {harness,admin,creator,outsider,draft} from './feature-fixture.mjs';
test('Only approved creators create; only administrator changes creator roles',async()=>{const h=harness();await assert.rejects(h.content.create(creator,'a'.repeat(20)),e=>e.status===403);await h.content.request(creator);await assert.rejects(h.content.grant(outsider,creator.userId,'creator'),e=>e.status===403);await h.content.grant(admin,creator.userId,'creator');assert.equal(await h.content.role(creator),'creator');await assert.rejects(h.content.grant(admin,admin.userId,'reader'));});
test('Course create retries are idempotent and ownership is enforced',async()=>{const h=harness();await h.setupCreator();const c=await h.content.create(creator,'a'.repeat(20));assert.equal((await h.content.create(creator,'a'.repeat(20))).id,c.id);await h.content.request(outsider);await h.content.grant(admin,outsider.userId,'creator');await assert.rejects(h.content.detail(outsider,c.id),e=>e.status===403);assert.equal((await h.content.list(outsider)).courses.length,0);});
test('All required values, numeric bounds and unknown enum values reject malformed input',()=>{for(const change of [{title:' '},{subject:'other'},{ages:'18+'},{minutes:4},{price:-1},{price:2.2},{materials:[]},{steps:[]},{steps:[null]},{steps:[{...draft().steps[0],minutes:0}]},{steps:[{...draft().steps[0],minutes:'abc'}]},{description:'x'.repeat(3001)}])assert.throws(()=>validateContent({...draft(),...change}));assert.equal(validateContent(draft()).title,'Unicode café STEM')});
test('Simultaneous saves do not overwrite a newer revision',async()=>{const h=harness();await h.setupCreator();const c=await h.content.create(creator,'a'.repeat(20));const results=await Promise.allSettled([h.content.save(creator,c.id,0,draft()),h.content.save(creator,c.id,0,{...draft(),title:'Another version'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.status,409)});
test('Draft invisible; publication administrator-only; public catalog never includes premium lesson text',async()=>{const h=harness();await h.setupCreator();let c=await h.content.create(creator,'a'.repeat(20));c=await h.content.save(creator,c.id,c.revision,draft());assert.equal((await h.content.catalog()).length,0);await assert.rejects(h.content.transition(creator,c.id,c.revision,'publish'),e=>e.status===403);c=await h.content.transition(admin,c.id,c.revision,'publish');const p=(await h.content.catalog())[0];assert.equal(p.title,draft().title);assert.ok(!JSON.stringify(p).includes('Private'));assert.equal(p.steps,undefined);});
test('Draft edits leave public version stable until next review publication',async()=>{const h=harness();let c=await h.content.create(admin,'a'.repeat(20));c=await h.content.save(admin,c.id,0,draft());c=await h.content.transition(admin,c.id,c.revision,'publish');await h.content.save(admin,c.id,c.revision,{...draft(),title:'New title'});assert.equal((await h.content.catalog())[0].title,draft().title);});
test('Archived course hidden from sale; creator cannot undo archive through review',async()=>{const h=harness();await h.setupCreator();let c=await h.content.create(creator,'a'.repeat(20));c=await h.content.save(creator,c.id,0,draft());c=await h.content.transition(admin,c.id,c.revision,'publish');c=await h.content.transition(admin,c.id,c.revision,'archive');assert.equal((await h.content.catalog()).length,0);assert.equal((await h.content.catalog(true)).length,1);await assert.rejects(h.content.transition(creator,c.id,c.revision,'review'),e=>e.status===409);});
test('Premium publication requires PDFs and complete courses require ten processed video lessons',async()=>{const h=harness();let c=await h.content.create(admin,'a'.repeat(20));c=await h.content.save(admin,c.id,0,{...draft(),sample:false});await assert.rejects(h.content.transition(admin,c.id,c.revision,'publish'),/English plan/);});
test('Published lesson identities are append-only and cannot shift progress or media',async()=>{const h=harness();let c=await h.content.create(admin,'a'.repeat(20));c=await h.content.save(admin,c.id,0,draft());c=await h.content.transition(admin,c.id,c.revision,'publish');await assert.rejects(h.content.save(admin,c.id,c.revision,{...draft(),steps:[{...draft().steps[0],id:'different'}]}),/order/);const d=draft();d.steps.push({...d.steps[0],id:'lesson-two',title:'Next lesson'});assert.equal((await h.content.save(admin,c.id,c.revision,d)).draft.steps.length,2)});
test('Publication picks newest asset per slot; published asset protected; replacement releases old file',async()=>{const h=harness();let c=await h.content.create(admin,'a'.repeat(20));c=await h.content.save(admin,c.id,0,draft());const insert=(id,time)=>h.sql.prepare("INSERT INTO content_assets(id,course_id,owner_id,kind,lesson_index,language,name,mime,size,status,created_at) VALUES(?,?,?,'worksheet',0,'en','sheet.pdf','application/pdf',100,'ready',?)").run(id,c.id,admin.userId,time);insert('asset-a',1);c=await h.content.transition(admin,c.id,c.revision,'publish');await assert.rejects(h.content.remove(admin,'asset-a'),e=>e.status===409);insert('asset-b',2);c=await h.content.detail(admin,c.id);c=await h.content.transition(admin,c.id,c.revision,'publish');assert.deepEqual(JSON.parse(c.published_assets),['asset-b']);await h.content.remove(admin,'asset-a');assert.equal(h.sql.prepare('SELECT status FROM content_assets WHERE id=?').get('asset-a').status,'deleted');});
test('File metadata rejects invalid lesson, language, purpose and foreign course',async()=>{const h=harness();let c=await h.content.create(admin,'a'.repeat(20));c=await h.content.save(admin,c.id,0,draft());for(const change of [{lesson:-1},{lesson:1},{language:'xx'},{kind:'html'}])await assert.rejects(h.content.assetMeta(admin,{courseId:c.id,kind:'plan',language:'en',lesson:0,name:'document.pdf',...change}));assert.equal((await h.content.assetMeta(admin,{courseId:c.id,kind:'plan',language:'en',lesson:0,name:'../file.pdf'})).name,'.._file.pdf')});
test('Valid PDFs accepted, fake/encrypted/empty and nested JavaScript rejected',async()=>{const plain=await documentPdf([{title:'Hello',lines:['Teaching notes']}]);assert.equal(await validateFile(plain,'file.pdf','application/pdf','plan'),'application/pdf');await assert.rejects(validateFile(new Uint8Array([1,2]),'file.pdf','application/pdf','plan'));await assert.rejects(validateFile(plain,'file.png','application/pdf','plan'));const doc=await PDFDocument.create(),page=doc.addPage();page.node.set(PDFName.of('Annots'),doc.context.obj([{Type:'Annot',Subtype:'Link',Rect:[0,0,10,10],A:{S:'JavaScript',JS:PDFString.of('app.alert(1)')}}]));await assert.rejects(validateFile(await doc.save(),'file.pdf','application/pdf','plan'),/active content/);});
test('Broken images, invalid captions and oversized CSV rejected; formulas sanitized',async()=>{await assert.rejects(validateFile(new Uint8Array([137,80,78,71]),'a.png','image/png','image'));await assert.rejects(validateFile(new TextEncoder().encode('not captions'),'a.vtt','text/vtt','captions'));await assert.rejects(validateFile(new Uint8Array(500001),'a.csv','text/csv','supplies'));await assert.rejects(validateFile(new Uint8Array([255,254]),'a.vtt','text/vtt','captions'),e=>e.status===400);assert.equal(sanitizeCsv('Item,Quantity\n"=HYPERLINK(""bad"")",2'), '"Item","Quantity"\r\n"\'=HYPERLINK(""bad"")","2"');});
test('Long Unicode documents paginate, merge and produce valid watermarked PDFs',async()=>{const bytes=await documentPdf([{title:'Café science',lines:Array.from({length:250},(_,i)=>'Line '+i+' — observe and explain the result.')}],'QA educator');const doc=await PDFDocument.load(bytes);assert.ok(doc.getPageCount()>3);const bundle=await bundlePdf([bytes],await documentPdf([{title:'Materials',lines:['Paper']}]),'QA educator');assert.equal((await PDFDocument.load(bundle)).getPageCount(),doc.getPageCount()+1)});

test('Upload completion fences the original revision and lesson identity, including the first file',async()=>{const h=harness();let c=await h.content.create(admin,'b'.repeat(20));c=await h.content.save(admin,c.id,0,draft());const m=await h.content.assetMeta(admin,{courseId:c.id,kind:'worksheet',language:'en',lesson:0,name:'sheet.pdf'});c=await h.content.save(admin,c.id,c.revision,{...draft(),steps:[{...draft().steps[0],id:'new-first'}]});const a={id:'upload-race',mime:'application/pdf',size:100,key:'test',status:'ready'};await assert.rejects(h.content.attachAsset(admin,m,a),e=>e.status===409);assert.equal(h.sql.prepare('SELECT count(*) n FROM content_assets').get().n,0);assert.equal((await h.content.detail(admin,c.id)).revision,c.revision);const fresh=await h.content.assetMeta(admin,{courseId:c.id,kind:'worksheet',language:'en',lesson:0,name:'sheet.pdf'});await h.content.attachAsset(admin,fresh,a);assert.equal((await h.content.detail(admin,c.id)).revision,c.revision+1);});
test('PDF file attachment annotations are rejected even without a name tree',async()=>{const doc=await PDFDocument.create(),page=doc.addPage(),stream=doc.context.flateStream(new TextEncoder().encode('Harmless fixture'),{Type:'EmbeddedFile'}),ref=doc.context.register(stream);page.node.set(PDFName.of('Annots'),doc.context.obj([{Type:'Annot',Subtype:'FileAttachment',Rect:[0,0,10,10],FS:{Type:'Filespec',F:PDFString.of('fixture.txt'),EF:{F:ref}}}]));await assert.rejects(validateFile(await doc.save(),'file.pdf','application/pdf','plan'),/attachments/);});

test('PDF Book is a first-class format with a required private book PDF',async()=>{const h=harness();let c=await h.content.create(admin,'book-test-key-123456');c=await h.content.save(admin,c.id,0,{...draft(),format:'PDF Book',sample:false});await assert.rejects(h.content.transition(admin,c.id,c.revision,'publish'),/book/);const m=await h.content.assetMeta(admin,{courseId:c.id,kind:'book',language:'en',lesson:0,name:'book.pdf'});await h.content.attachAsset(admin,m,{id:'book-asset',mime:'application/pdf',size:100,key:'book',status:'ready'});c=await h.content.detail(admin,c.id);c=await h.content.transition(admin,c.id,c.revision,'publish');assert.equal((await h.content.catalog())[0].format,'PDF Book');});
test('Published samples cannot be converted into premium resources and strand demo readers',async()=>{const h=harness();let c=await h.content.create(admin,'sample-key-12345678');c=await h.content.save(admin,c.id,0,draft());c=await h.content.transition(admin,c.id,c.revision,'publish');await assert.rejects(h.content.save(admin,c.id,c.revision,{...draft(),sample:false}),/separate premium/);});
test('A removed video cannot be resurrected by a late provider status response',async()=>{const h=harness();let c=await h.content.create(admin,'video-test-key-12345');c=await h.content.save(admin,c.id,0,draft());const m=await h.content.assetMeta(admin,{courseId:c.id,kind:'video',language:'es',lesson:0,name:'video.mp4'});await h.content.attachAsset(admin,m,{id:'video-asset',mime:'video/mp4',size:0,providerId:'up_fixture',status:'uploading'});await h.content.remove(admin,'video-asset');const revision=(await h.content.detail(admin,c.id)).revision;await assert.rejects(h.content.updateVideo(admin,'video-asset','uploading','ready','playback'),e=>e.status===404);assert.equal((await h.content.detail(admin,c.id)).revision,revision);});
