import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {contentService} from '../lib/content.mjs';
import {programBilling} from '../lib/program-billing.mjs';
import {emailService} from '../lib/email.mjs';
export const admin={userId:'qa-admin',displayName:'QA administrator',email:'qa-admin@example.test'},creator={userId:'qa-creator',displayName:'QA creator',email:'qa-creator@example.test'},outsider={userId:'qa-outsider',displayName:'QA outsider',email:'qa-outsider@example.test'};
export const draft=()=>({title:'Unicode café STEM',subject:'physics',ages:'6–10',format:'Lesson plan',minutes:30,price:900,supply:'Household',description:'A sample course for regression testing.',outcomes:'Observe and explain a change.',safety:'Adult supervision; review all supplies.',standards:'',track:'single',sample:true,materials:['Paper','Tape'],steps:[{id:'lesson-one',title:'Explore',prep:'Private preparation sentinel',instructions:'Private instructions sentinel',minutes:30}]});
export function harness(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8'));const db={prepare(text){const wrap=args=>({async first(){return sql.prepare(text).get(...args)??null},async all(){return {results:sql.prepare(text).all(...args)}},async run(){return {meta:{changes:sql.prepare(text).run(...args).changes}}},exec(){return {meta:{changes:sql.prepare(text).run(...args).changes}}}});return {bind(...args){return wrap(args)},...wrap([])}} ,async batch(items){sql.exec('BEGIN');try{const results=items.map(s=>s.exec());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};let time=Date.UTC(2026,9,7,15);const settings={CONTENT_ADMIN_USER_IDS:admin.userId,STRIPE_SECRET_KEY:'sk_test_fixture',SITE_ORIGIN:'https://example.test'},calls=[],sessions=new Map(),invoices=new Map(),idem=new Map();let sequence=0;const stripe=async(path,form,key)=>{calls.push({path,form:form?Object.fromEntries(form):null,key});if(form&&key&&idem.has(key))return structuredClone(idem.get(key));let result;if(path==='checkout/sessions'){const id='cs_test_'+(++sequence);result={id,status:'open',payment_status:'unpaid',livemode:false,mode:'payment',currency:'usd',amount_total:Number(form.get('line_items[0][price_data][unit_amount]')),amount_subtotal:Number(form.get('line_items[0][price_data][unit_amount]')),client_reference_id:form.get('client_reference_id'),metadata:{license_id:form.get('metadata[license_id]'),user_id:form.get('metadata[user_id]')},url:'https://checkout.stripe.com/test'};sessions.set(id,result);}else if(path.startsWith('checkout/sessions/'))return structuredClone(sessions.get(path.split('/')[2]));else if(path==='customers')result={id:'cus_'+(++sequence),livemode:false};else if(path==='invoices'){result={id:'in_'+(++sequence),status:'draft',livemode:false,customer:form.get('customer'),metadata:{po_id:form.get('metadata[po_id]')},currency:'usd',subtotal:0,total:0,amount_paid:0,amount_remaining:0,lines:{data:[]}};invoices.set(result.id,result);}else if(path==='invoiceitems'){const i=invoices.get(form.get('invoice'));i.subtotal+=Number(form.get('amount'));i.total=i.subtotal;i.amount_remaining=i.total;i.lines.data.push({amount:Number(form.get('amount'))});result={id:'ii_'+(++sequence)};}else if(path.startsWith('invoices/')){const [,id,action]=path.split('/');const i=invoices.get(id);if(action==='finalize')Object.assign(i,{status:'open',hosted_invoice_url:'https://invoice.stripe.com/test',invoice_pdf:'https://files.stripe.com/test.pdf'});result=i;}else throw new Error('Unexpected Stripe path: '+path);if(key)idem.set(key,structuredClone(result));return structuredClone(result);};
 const content=contentService({db,settings,now:()=>time}),email=emailService({db,settings,now:()=>time}),program=programBilling({db,stripe,settings,content,catalog:async()=>[{id:'example-course'}],email,now:()=>time});
 async function setupCreator(){await content.request(creator);await content.grant(admin,creator.userId,'creator');}
 function school(id='school-one',owner=creator){sql.prepare('INSERT INTO schools(id,owner_id,name,created_at) VALUES(?,?,?,?)').run(id,owner.userId,id,time);sql.prepare('INSERT INTO school_members(school_id,user_id,name,joined_at) VALUES(?,?,?,?)').run(id,owner.userId,owner.displayName,time);return id;}
 return {db,sql,settings,content,program,email,stripe,calls,sessions,invoices,setupCreator,school,get time(){return time},advance(ms){time+=ms}};
}
