import test from 'node:test';
import assert from 'node:assert/strict';
import {harness,creator,outsider} from './feature-fixture.mjs';
import {individualBilling} from '../lib/individual-billing.mjs';
const key='checkout-key-1234567890';
function setup(){
 const h=harness(),calls=[],sessions=new Map(),idem=new Map();let serial=0,failOnce=false,beforeReturn=null;
 let products=[{id:'bridge',title:'Paper bridge',price:900,materials:['Paper']}];
 h.sql.prepare('INSERT INTO carts(user_id,items,updated_at) VALUES(?,?,?)').run(creator.userId,'["bridge"]',h.time);
 const stripe=async(path,form,idempotency)=>{
  calls.push({path,form:form?Object.fromEntries(form):null,key:idempotency});
  let result;
  if(path==='checkout/sessions'){
   assert.ok(h.sql.prepare('SELECT id FROM orders WHERE id=?').get(form.get('client_reference_id')),'order must exist before Stripe is called');
   if(idem.has(idempotency))return structuredClone(idem.get(idempotency));
   let total=0;for(const [k,v]of form)if(k.endsWith('[unit_amount]'))total+=Number(v);
   result={id:'cs_test_'+(++serial),status:'open',payment_status:'unpaid',mode:'payment',livemode:false,currency:'usd',amount_subtotal:total,amount_total:total,total_details:{amount_tax:0,amount_discount:0},client_reference_id:form.get('client_reference_id'),metadata:{user_id:form.get('metadata[user_id]')},url:'https://checkout.stripe.com/c/test_fixture'};
   sessions.set(result.id,result);idem.set(idempotency,structuredClone(result));
   if(failOnce){failOnce=false;throw new Error('Simulated lost Stripe response')}
   if(beforeReturn)await beforeReturn();
  }else{
   const id=path.split('/')[2].split('?')[0];result=sessions.get(id);if(!result)throw new Error('Unknown session');if(path.endsWith('/expire'))result.status='expired';
  }
  return structuredClone(result);
 };
 const service=individualBilling({db:h.db,stripe,settings:h.settings,catalog:async()=>products,now:()=>h.time});
 const paid=id=>Object.assign(sessions.get(id),{status:'complete',payment_status:'paid',invoice:{hosted_invoice_url:'https://invoice.stripe.com/i/test',invoice_pdf:'https://files.stripe.com/test.pdf'}});
 return {...h,service,calls,sessions,paid,get products(){return products},set products(v){products=v},loseResponse(){failOnce=true},delay(fn){beforeReturn=fn}};
}
test('Individual checkout persists immutable order before Stripe; amount and return URLs are server-owned',async()=>{const h=setup(),r=await h.service.checkout(creator,key),o=h.sql.prepare('SELECT * FROM orders').get();assert.equal(o.status,'pending');assert.equal(o.total,900);assert.equal(o.session_id,'cs_test_1');assert.equal(r.url,'https://checkout.stripe.com/c/test_fixture');const f=h.calls[0].form;assert.equal(f['line_items[0][price_data][unit_amount]'],'900');assert.equal(f['invoice_creation[enabled]'],'true');assert.equal(f['line_items[0][price_data][tax_behavior]'],'exclusive');});
test('Missing/live Stripe keys fail before order creation',async()=>{for(const value of ['', 'sk_live_fake']){const h=setup();h.settings.STRIPE_SECRET_KEY=value;await assert.rejects(h.service.checkout(creator,key),e=>e.status===503);assert.equal(h.calls.length,0);assert.equal(h.sql.prepare('SELECT count(*) n FROM orders').get().n,0)}});
test('Different browser keys and price/cart edits reuse the existing open checkout',async()=>{const h=setup();await h.service.checkout(creator,key);h.products=[{...h.products[0],price:1900,title:'Changed'}];h.sql.prepare('UPDATE carts SET items=?').run('[]');await h.service.checkout(creator,'another-key-1234567');assert.equal(h.calls.filter(c=>c.path==='checkout/sessions').length,1);assert.equal(h.sql.prepare('SELECT count(*) n FROM orders').get().n,1);assert.equal(JSON.parse(h.sql.prepare('SELECT snapshot FROM orders').get().snapshot).lines[0].price,900)});
test('Lost provider response retries the same parameters and idempotency key',async()=>{const h=setup();h.loseResponse();await assert.rejects(h.service.checkout(creator,key));h.products=[{...h.products[0],price:2000}];await h.service.checkout({...creator,email:'changed@example.test'},'different-key-123456');assert.deepEqual(h.calls[0],h.calls[1]);assert.equal(h.sessions.size,1)});
test('Concurrent browser checkouts produce only one provider session',async()=>{const h=setup();const r=await Promise.allSettled([h.service.checkout(creator,key),h.service.checkout(creator,'parallel-key-123456')]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(h.calls.filter(c=>c.path==='checkout/sessions').length,1)});
test('Ambiguous attempt beyond retention is blocked without a new charge',async()=>{const h=setup();h.loseResponse();await assert.rejects(h.service.checkout(creator,key));h.advance(24*3600000);const count=h.calls.length;await assert.rejects(h.service.checkout(creator,key),/needs review/);assert.equal(h.calls.length,count)});
test('Known expired checkout releases the account for a new checkout',async()=>{const h=setup();await h.service.checkout(creator,key);h.sessions.get('cs_test_1').status='expired';await h.service.checkout(creator,'next-checkout-123456');assert.equal(h.sessions.size,2);assert.equal(h.sql.prepare('SELECT status FROM orders WHERE id=?').get(creator.userId+':'+key).status,'expired')});
test('Paid confirmation recovers missing session binding and is idempotent',async()=>{const h=setup();await h.service.checkout(creator,key);h.sql.prepare('UPDATE orders SET session_id=NULL').run();h.paid('cs_test_1');assert.equal((await h.service.confirm(creator,'cs_test_1')).status,'complete');await h.service.confirm(creator,'cs_test_1');assert.equal(h.sql.prepare('SELECT count(*) n FROM entitlements').get().n,1);assert.equal(h.sql.prepare('SELECT items FROM carts').get().items,'[]');assert.equal(h.sql.prepare('SELECT invoice_pdf FROM orders').get().invoice_pdf,'https://files.stripe.com/test.pdf')});
test('Paid webhook recovers order before session binding and never trusts payload amounts',async()=>{const h=setup();await h.service.checkout(creator,key);h.sql.prepare('UPDATE orders SET session_id=NULL').run();h.paid('cs_test_1');await h.service.webhook({type:'checkout.session.completed',data:{object:{...h.sessions.get('cs_test_1'),amount_total:1}}});assert.equal(h.sql.prepare('SELECT status FROM orders').get().status,'complete')});
test('Unpaid session grants no access and another account cannot confirm it',async()=>{const h=setup();await h.service.checkout(creator,key);await assert.rejects(h.service.confirm(outsider,'cs_test_1'),e=>e.status===404);assert.equal((await h.service.confirm(creator,'cs_test_1')).status,'pending');assert.equal(h.sql.prepare('SELECT count(*) n FROM entitlements').get().n,0)});
test('Live, foreign, discounted, wrong-currency and changed-price sessions never grant access',async()=>{for(const change of [{livemode:true},{currency:'eur'},{amount_total:1},{client_reference_id:'foreign'},{metadata:{user_id:'wrong'}},{total_details:{amount_tax:0,amount_discount:1}}]){const h=setup();await h.service.checkout(creator,key);h.paid('cs_test_1');Object.assign(h.sessions.get('cs_test_1'),change);await assert.rejects(h.service.confirm(creator,'cs_test_1'));assert.equal(h.sql.prepare('SELECT count(*) n FROM entitlements').get().n,0)}});
test('Automatic tax preserves saved base price and stores verified gross payment',async()=>{const h=setup();h.settings.STRIPE_TAX_ENABLED='true';await h.service.checkout(creator,key);const s=h.paid('cs_test_1');Object.assign(s,{amount_total:972,total_details:{amount_tax:72,amount_discount:0},automatic_tax:{enabled:true,status:'complete'}});await h.service.confirm(creator,'cs_test_1');assert.equal(h.sql.prepare('SELECT paid_total FROM orders').get().paid_total,972)});
test('Lease expiry fences a late Stripe response',async()=>{const h=setup();h.delay(async()=>h.advance(120001));await assert.rejects(h.service.checkout(creator,key),e=>e.status===409);assert.equal(h.sql.prepare('SELECT session_id FROM orders').get().session_id,null);assert.equal(h.sessions.size,1)});
test('Cancel expires only the owned pending checkout; paid returns still fulfill',async()=>{const h=setup();const r=await h.service.checkout(creator,key);await assert.rejects(h.service.cancel(outsider,r.orderId),e=>e.status===404);assert.equal((await h.service.cancel(creator,r.orderId)).status,'expired');const next=await h.service.checkout(creator,'next-key-123456789');h.paid('cs_test_2');assert.equal((await h.service.cancel(creator,next.orderId)).status,'complete')});
test('An existing demo request key cannot be reused for Stripe',async()=>{const h=setup();h.sql.prepare("INSERT INTO orders(id,user_id,items,total,status,mode,created_at) VALUES(?,?,?,?,'complete','demo',?)").run(creator.userId+':'+key,creator.userId,'["bridge"]',900,h.time);await assert.rejects(h.service.checkout(creator,key),e=>e.status===409);h.settings.STRIPE_SECRET_KEY='';await assert.rejects(h.service.checkout(creator,key),e=>e.status===409);assert.equal(h.calls.length,0)});

test('Zero-tax automatic-tax orders still require completed calculation',async()=>{for(const status of ['failed','requires_location_inputs','complete']){const h=setup();h.settings.STRIPE_TAX_ENABLED='true';await h.service.checkout(creator,key);h.paid('cs_test_1');h.sessions.get('cs_test_1').automatic_tax={enabled:true,status};if(status==='complete')assert.equal((await h.service.confirm(creator,'cs_test_1')).status,'complete');else await assert.rejects(h.service.confirm(creator,'cs_test_1'),/tax calculation/);}});
test('Later receipt refresh cannot erase previously verified invoice links',async()=>{const h=setup();await h.service.checkout(creator,key);h.paid('cs_test_1');await h.service.confirm(creator,'cs_test_1');h.sessions.get('cs_test_1').invoice=null;await h.service.confirm(creator,'cs_test_1');assert.equal(h.sql.prepare('SELECT invoice_pdf FROM orders').get().invoice_pdf,'https://files.stripe.com/test.pdf')});

test('Unknown or foreign confirmations fail before contacting Stripe',async()=>{const h=setup();await assert.rejects(h.service.confirm(creator,'cs_test_fake'),e=>e.status===404);assert.equal(h.calls.length,0);await h.service.checkout(creator,key);const count=h.calls.length;await assert.rejects(h.service.confirm(outsider,'cs_test_1'),e=>e.status===404);assert.equal(h.calls.length,count)});
