import {schoolBilling} from '../lib/school-billing.mjs';
import {programBilling} from '../lib/program-billing.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {harness,admin,creator,outsider} from './feature-fixture.mjs';
const form=(kind='quote')=>({kind,name:'Test Director',email:'director@example.test',organization:'QA School',role:'daycare',sites:1,po:kind==='po'?'PO-100':'',notes:'Testing only',consent:true,net30:true,taxExemptionRequested:false,key:'request-key-12345678',addressLine1:'123 Test Street',addressCity:'Test City',addressState:'TX',addressPostal:'00000',addressCountry:'US'});
const seasonal=schoolId=>({schoolId,scope:'subject:physics',start:'2026-10-07',consent:true,key:'season-key-123456789'});
test('Quotes persist price, validity, scope and stable ID; retries do not duplicate',async()=>{const h=harness(),b=form(),r=await h.program.submit(creator,b);assert.equal((await h.program.submit(creator,b)).id,r.id);const row=await h.program.requestRow(creator,r.id),data=JSON.parse(row.data);assert.equal(row.amount,39900);assert.equal(data.validUntil,h.time+30*86400000);assert.match(data.scope,/physical/);await assert.rejects(h.program.submit(creator,{...b,sites:2}),e=>e.status===409);await assert.rejects(h.program.requestRow(outsider,r.id),e=>e.status===404);});
test('Quote amount server-owned and invalid site counts rejected',async()=>{const h=harness();const r=await h.program.submit(creator,{...form(),sites:10,amount:1});assert.equal((await h.program.requestRow(creator,r.id)).amount,399000);for(const sites of [0,-1,1.1,1001])await assert.rejects(h.program.submit(creator,{...form(),sites}));});
test('PO requires director ownership, PO number, one location, consent and Net30 request',async()=>{const h=harness(),schoolId=h.school();for(const change of [{schoolId:'unknown'},{po:''},{sites:2},{consent:false},{net30:false}])await assert.rejects(h.program.submit(creator,{...form('po'),schoolId,...change}));await assert.rejects(h.program.submit(outsider,{...form('po'),schoolId}),e=>e.status===403);});
test('PO submission and review do not grant access before verified invoice payment',async()=>{const h=harness(),schoolId=h.school(),r=await h.program.submit(creator,{...form('po'),schoolId});assert.equal(h.sql.prepare('SELECT count(*) AS n FROM licenses').get().n,0);await h.program.review(admin,{id:r.id,action:'approve',note:'QA approved'});assert.equal(h.sql.prepare('SELECT count(*) AS n FROM licenses').get().n,0);const row=await h.program.requestRow(creator,r.id),i=h.invoices.get(row.invoice_id);Object.assign(i,{status:'paid',amount_paid:i.total,amount_remaining:0});await h.program.refresh(creator,r.id);assert.equal(h.sql.prepare('SELECT count(*) AS n FROM licenses').get().n,1);const license=h.sql.prepare('SELECT * FROM licenses').get();h.advance(1000);await h.program.refresh(creator,r.id);assert.equal(h.sql.prepare('SELECT ends_at FROM licenses').get().ends_at,license.ends_at);});
test('Invoice items attach to the exact invoice and repeated approval cannot duplicate items',async()=>{const h=harness(),schoolId=h.school(),r=await h.program.submit(creator,{...form('po'),schoolId});await h.program.review(admin,{id:r.id,action:'approve',note:'QA approved'});await h.program.review(admin,{id:r.id,action:'approve',note:'QA approved again'});const row=await h.program.requestRow(creator,r.id);assert.equal(h.invoices.get(row.invoice_id).lines.data.length,1);assert.equal(h.calls.find(c=>c.path==='invoiceitems').form.invoice,row.invoice_id);assert.equal(h.calls.find(c=>c.path==='invoices').form.days_until_due,'30');assert.equal(h.calls.find(c=>c.path==='invoices').form.auto_advance,'false');});
test('Only administrator approves or rejects PO; rejection needs a reason',async()=>{const h=harness(),schoolId=h.school(),r=await h.program.submit(creator,{...form('po'),schoolId});await assert.rejects(h.program.review(creator,{id:r.id,action:'approve',note:'No'}),e=>e.status===403);await assert.rejects(h.program.review(admin,{id:r.id,action:'reject',note:''}));await h.program.review(admin,{id:r.id,action:'reject',note:'Need corrected scope'});await assert.rejects(h.program.review(admin,{id:r.id,action:'approve',note:'Retry'}),e=>e.status===409);assert.equal(h.calls.length,0);});
test('Exemption cannot be self-approved; certificate and explicit administrator decision required',async()=>{const h=harness(),schoolId=h.school(),r=await h.program.submit(creator,{...form('po'),schoolId,taxExemptionRequested:true});await assert.rejects(h.program.review(admin,{id:r.id,action:'approve',note:'Reviewed',exemptionApproved:true}),/certificate/);h.sql.prepare("UPDATE purchase_requests SET certificate_key='test-private' WHERE id=?").run(r.id);await assert.rejects(h.program.review(admin,{id:r.id,action:'approve',note:'Reviewed'}),/exemption/);await h.program.review(admin,{id:r.id,action:'approve',note:'Reviewed',exemptionApproved:true});assert.equal(h.calls.find(c=>c.path==='customers').form.tax_exempt,'exempt');});
test('Automatic tax needs billing location and sends it only to the owned test customer',async()=>{const h=harness(),schoolId=h.school();h.settings.STRIPE_TAX_ENABLED='true';let r=await h.program.submit(creator,{...form('po'),schoolId,addressPostal:''});await assert.rejects(h.program.review(admin,{id:r.id,action:'approve',note:'Approved'}),/billing address/);r=await h.program.submit(creator,{...form('po'),schoolId,key:'corrected-key-12345678'});await h.program.review(admin,{id:r.id,action:'approve',note:'Approved'});assert.equal(h.calls.find(c=>c.path==='customers').form['address[country]'],'US');assert.equal(h.calls.find(c=>c.path==='invoices').form['automatic_tax[enabled]'],'true')});
test('Underpaid/foreign/live invoices never grant an annual license',async()=>{for(const mutation of [i=>i.amount_paid=1,i=>i.amount_remaining=1,i=>i.customer='foreign',i=>i.livemode=true,i=>i.subtotal=1]){const h=harness(),schoolId=h.school(),r=await h.program.submit(creator,{...form('po'),schoolId});await h.program.review(admin,{id:r.id,action:'approve',note:'Approved'});const row=await h.program.requestRow(creator,r.id),i=h.invoices.get(row.invoice_id);Object.assign(i,{status:'paid',amount_paid:i.total,amount_remaining:0});mutation(i);await assert.rejects(h.program.refresh(creator,r.id));assert.equal(h.sql.prepare('SELECT count(*) AS n FROM licenses').get().n,0)}});
test('Seasonal date, scope, ownership, test key and consent validation',async()=>{const h=harness(),schoolId=h.school();for(const change of [{scope:'all'},{start:'2020-01-01'},{start:'2030-01-01'},{start:'bad'},{consent:false}])await assert.rejects(h.program.seasonal(creator,{...seasonal(schoolId),...change}));await assert.rejects(h.program.seasonal(outsider,seasonal(schoolId)),e=>e.status===403);h.settings.STRIPE_SECRET_KEY='sk_live_fake';await assert.rejects(h.program.seasonal(creator,seasonal(schoolId)));assert.equal(h.calls.length,0)});
test('Seasonal checkout fixes price/scope/dates and safely reuses a pending checkout across browser keys',async()=>{const h=harness(),schoolId=h.school(),b=seasonal(schoolId);const first=await h.program.seasonal(creator,b),second=await h.program.seasonal(creator,{...b,key:'different-key-12345678'});assert.equal(first.url,second.url);assert.equal(h.sessions.size,1);const f=h.calls.find(c=>c.path==='checkout/sessions').form;assert.equal(f['line_items[0][price_data][unit_amount]'],'14900');assert.equal(f.mode,'payment');const row=h.sql.prepare('SELECT * FROM licenses').get();assert.equal(row.ends_at-row.starts_at,90*86400000);});
test('Seasonal paid confirmation is owned, amount-checked, idempotent and time-window preserving',async()=>{const h=harness(),schoolId=h.school();await h.program.seasonal(creator,seasonal(schoolId));const row=h.sql.prepare('SELECT * FROM licenses').get(),s=h.sessions.get(row.session_id);await assert.rejects(h.program.confirm(outsider,s.id),e=>e.status===404);assert.equal((await h.program.confirm(creator,s.id)).status,'pending');Object.assign(s,{status:'complete',payment_status:'paid',amount_total:1});await assert.rejects(h.program.confirm(creator,s.id));s.amount_total=14900;await h.program.confirm(creator,s.id);h.advance(1000);await h.program.confirm(creator,s.id);assert.equal(h.sql.prepare('SELECT ends_at FROM licenses').get().ends_at,row.ends_at);assert.equal(h.sql.prepare('SELECT status FROM licenses').get().status,'paid');});
test('Webhook recovers paid seasonal session whose local session ID write was lost',async()=>{const h=harness(),schoolId=h.school();await h.program.seasonal(creator,seasonal(schoolId));const row=h.sql.prepare('SELECT * FROM licenses').get(),s=h.sessions.get(row.session_id);Object.assign(s,{status:'complete',payment_status:'paid'});h.sql.prepare('UPDATE licenses SET session_id=NULL WHERE id=?').run(row.id);await h.program.webhook({type:'checkout.session.completed',data:{object:s}});const saved=h.sql.prepare('SELECT * FROM licenses').get();assert.equal(saved.status,'paid');assert.equal(saved.session_id,s.id)});
test('Annual subscription prevents overlapping seasonal purchase and annual PO invoice',async()=>{const h=harness(),schoolId=h.school();h.sql.prepare("UPDATE schools SET subscription_id='sub_test',status='active' WHERE id=?").run(schoolId);await assert.rejects(h.program.seasonal(creator,seasonal(schoolId)),e=>e.status===409);const r=await h.program.submit(creator,{...form('po'),schoolId});await assert.rejects(h.program.review(admin,{id:r.id,action:'approve',note:'Reviewed'}),e=>e.status===409);assert.equal(h.calls.length,0)});
test('Missing email provider queues acknowledgment without falsely reporting delivery',async()=>{const h=harness();const r=await h.program.submit(creator,form());assert.equal(r.email.status,'queued');assert.equal(h.sql.prepare('SELECT status FROM email_outbox').get().status,'queued')});

test('Pending annual PO reserves billing against a second PO and annual subscription',async()=>{const h=harness(),schoolId=h.school();const one=await h.program.submit(creator,{...form('po'),schoolId}),two=await h.program.submit(creator,{...form('po'),schoolId,key:'other-po-key-123456'});await h.program.review(admin,{id:one.id,action:'approve',note:'Approved'});const calls=h.calls.length;await assert.rejects(h.program.review(admin,{id:two.id,action:'approve',note:'Second'}),e=>e.status===409);const schools=schoolBilling({db:h.db,stripe:h.stripe,settings:h.settings,now:()=>h.time});await assert.rejects(schools.checkout(creator,schoolId,true),e=>e.status===409);assert.equal(h.calls.length,calls);assert.equal(h.calls.find(c=>c.path==='invoiceitems').form.tax_behavior,'exclusive');});
test('Pending subscription reserves billing against PO approval; expired checkout releases it',async()=>{const h=harness(),schoolId=h.school(),r=await h.program.submit(creator,{...form('po'),schoolId});h.sql.prepare('INSERT INTO school_checkouts(school_id,attempt,session_id,created_at) VALUES(?,?,?,?)').run(schoolId,'test','cs_test_annual',h.time);h.sessions.set('cs_test_annual',{id:'cs_test_annual',status:'open',payment_status:'unpaid'});await assert.rejects(h.program.review(admin,{id:r.id,action:'approve',note:'Reviewed'}),e=>e.status===409);h.sessions.get('cs_test_annual').status='expired';await h.program.review(admin,{id:r.id,action:'approve',note:'Reviewed'});assert.equal(h.sql.prepare('SELECT count(*) n FROM school_checkouts').get().n,0);});
test('Voided invoice releases annual billing reservation after verified refresh',async()=>{const h=harness(),schoolId=h.school(),one=await h.program.submit(creator,{...form('po'),schoolId}),two=await h.program.submit(creator,{...form('po'),schoolId,key:'other-po-key-123456'});await h.program.review(admin,{id:one.id,action:'approve',note:'First'});const row=await h.program.requestRow(creator,one.id);h.invoices.get(row.invoice_id).status='void';await h.program.refresh(creator,one.id);await h.program.review(admin,{id:two.id,action:'approve',note:'Replacement'});assert.equal((await h.program.requestRow(creator,two.id)).status,'invoiced');});

test('Stale canceled school cannot release a newly completed annual checkout for PO approval',async()=>{for(const payment_status of ['paid','unpaid']){const h=harness(),schoolId=h.school(),r=await h.program.submit(creator,{...form('po'),schoolId});h.sql.prepare("UPDATE schools SET subscription_id='sub_old',status='canceled' WHERE id=?").run(schoolId);h.sql.prepare('INSERT INTO school_checkouts(school_id,attempt,session_id,created_at) VALUES(?,?,?,?)').run(schoolId,'attempt-new','cs_test_new',h.time);h.sessions.set('cs_test_new',{id:'cs_test_new',status:'complete',payment_status,subscription:'sub_new'});await assert.rejects(h.program.review(admin,{id:r.id,action:'approve',note:'Review'}),e=>e.status===409);assert.equal(h.invoices.size,0)}});

test('Changing seasonal dates never silently reuses old dates; expired checkout releases reservation',async()=>{const h=harness(),schoolId=h.school(),b=seasonal(schoolId);await h.program.seasonal(creator,b);await assert.rejects(h.program.seasonal(creator,{...b,start:'2026-11-01',key:'changed-dates-123456'}),e=>e.status===409);assert.equal(h.sessions.size,1);h.sessions.get('cs_test_1').status='expired';await h.program.seasonal(creator,{...b,start:'2026-11-01',key:'changed-dates-123456'});assert.equal(h.sessions.size,2)});
test('Seasonal lost-response retries preserve email, return URLs, tax and receipt snapshot',async()=>{const h=harness(),schoolId=h.school(),b=seasonal(schoolId);let fail=true;const p=programBilling({db:h.db,settings:h.settings,content:h.content,catalog:async()=>[],email:h.email,now:()=>h.time,stripe:async(path,form,key)=>{const r=await h.stripe(path,form,key);if(fail&&form){fail=false;throw new Error('Lost response')}return r}});await assert.rejects(p.seasonal(creator,b));const original=h.calls[0].form;h.settings.SITE_ORIGIN='https://changed.test';h.settings.STRIPE_TAX_ENABLED='true';await p.seasonal({...creator,email:'changed@example.test'},b);assert.deepEqual(h.calls.filter(c=>c.form).at(-1).form,original);const row=h.sql.prepare('SELECT * FROM licenses').get();assert.equal(JSON.parse(row.checkout_data).schoolName,schoolId);const session=h.sessions.get(row.session_id);Object.assign(session,{status:'complete',payment_status:'paid'});await p.confirm(creator,session.id);const paid=h.sql.prepare('SELECT * FROM licenses').get();assert.equal(paid.paid_total,14900);assert.equal(paid.paid_at,h.time)});
