import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {schoolBilling,schoolAccess,paidThrough,validateSubscription,SCHOOL_PLAN} from '../lib/school-billing.mjs';

const director={userId:'director',displayName:'School Director',email:'director@example.test'},teacher={userId:'teacher',displayName:'Teacher',email:'teacher@example.test'},other={userId:'other',displayName:'Other',email:'other@example.test'};
function harness(){
 const sql=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8'));
 const db={prepare(text){return {bind(...args){return {async first(){return sql.prepare(text).get(...args)??null},async all(){return {results:sql.prepare(text).all(...args)}},async run(){return {meta:{changes:sql.prepare(text).run(...args).changes}}},exec(){return sql.prepare(text).run(...args)}}}}},async batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>s.exec());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};
 let time=Date.now(),sub=null,session=null,hook=null;const calls=[],sessions=new Map(),customers=new Map();
 const stripe=async(path,form,key)=>{
  calls.push({path,form:form?Object.fromEntries(form):null,key});if(hook){const h=hook;hook=null;await h(path)}
  if(path==='customers'){if(!customers.has(key))customers.set(key,{id:'cus_test'+customers.size,livemode:false});return customers.get(key)}
  if(path==='checkout/sessions'){if(!sessions.has(key)){session={id:'cs_test_'+sessions.size,livemode:false,mode:form.get('mode'),status:'open',payment_status:'unpaid',customer:form.get('customer'),client_reference_id:form.get('client_reference_id'),metadata:{school_id:form.get('metadata[school_id]'),attempt:form.get('metadata[attempt]')},url:'https://checkout.stripe.com/test'};sessions.set(key,session);}return structuredClone(sessions.get(key))}
  if(path.startsWith('checkout/sessions/'))return structuredClone(session);
  if(path.startsWith('subscriptions/')){if(!sub)throw new Error('No subscription');return structuredClone(sub)}
  if(path==='billing_portal/configurations')return {id:'bpc_test',livemode:false};
  if(path==='billing_portal/sessions')return {url:'https://billing.stripe.com/test'};
  throw new Error('Unexpected fake Stripe path '+path);
 };
 const settings={STRIPE_SECRET_KEY:'sk_test_fixture_only',SITE_ORIGIN:'https://school.example.test'},service=schoolBilling({db,stripe,settings,now:()=>time});
 async function setup(){const {id}=await service.create(director,'Test School');return id;}
 async function paid(id){await service.checkout(director,id,true);const s=sql.prepare('SELECT * FROM schools WHERE id=?').get(id),start=Math.floor(time/1000),end=start+365*86400;
  sub={id:'sub_test',customer:s.customer_id,livemode:false,status:'active',cancel_at_period_end:false,metadata:{school_id:id,plan:SCHOOL_PLAN.id,attempt:session.metadata.attempt},items:{data:[{id:'si_test',quantity:1,current_period_start:start,current_period_end:end,price:{id:'price_test',unit_amount:39900,currency:'usd',recurring:{interval:'year',interval_count:1}}}]},latest_invoice:{id:'in_test',status:'paid',amount_remaining:0,amount_paid:39900,total:39900,currency:'usd',customer:s.customer_id,livemode:false,parent:{subscription_details:{subscription:'sub_test'}},lines:{data:[{pricing:{price_details:{price:'price_test'}},period:{start,end}}]}}};
  session.status='complete';session.payment_status='paid';session.subscription='sub_test';await service.confirm(director,session.id);return id;
 }
 return {sql,service,settings,calls,setup,paid,get sub(){return sub},get session(){return session},get time(){return time},advance(ms){time+=ms},hook(fn){hook=fn},row(id){return sql.prepare('SELECT * FROM schools WHERE id=?').get(id)},async sync(id){return service.manualRefresh(director,id)}};
}
test('School creation is durable and repeated creation keeps one director school',async()=>{const h=harness(),id=await h.setup();assert.equal((await h.service.create(director,'Different name')).id,id);const view=await h.service.view(director);assert.equal(view.schools.length,1);assert.equal(view.schools[0].members[0].role,'director');assert.equal(view.schools[0].access,false)});
test('Blank/overlong school names rejected',async()=>{const h=harness();for(const name of ['',null,'a'.repeat(121)])await assert.rejects(h.service.create(director,name))});
test('Missing/live keys and insecure return URLs block checkout without Stripe calls',async()=>{const h=harness(),id=await h.setup();for(const key of ['', 'sk_live_fixture']){h.settings.STRIPE_SECRET_KEY=key;await assert.rejects(h.service.checkout(director,id,true));}h.settings.STRIPE_SECRET_KEY='sk_test_fixture';h.settings.SITE_ORIGIN='http://example.test';await assert.rejects(h.service.checkout(director,id,true));assert.equal(h.calls.length,0)});
test('Annual recurring consent is required before checkout',async()=>{const h=harness(),id=await h.setup();await assert.rejects(h.service.checkout(director,id,false));assert.equal(h.calls.length,0)});
test('Only director can checkout, view portal, invite, refresh, revoke or remove',async()=>{const h=harness(),id=await h.setup();for(const action of [()=>h.service.checkout(other,id,true),()=>h.service.portal(other,id),()=>h.service.invite(other,id),()=>h.service.manualRefresh(other,id),()=>h.service.revoke(other,id,'bad'),()=>h.service.remove(other,id,'teacher')])await assert.rejects(action,e=>e.status===403);assert.equal(h.calls.length,0)});
test('Checkout sends annual server price, fixed quantity and school metadata',async()=>{const h=harness(),id=await h.setup();await h.service.checkout(director,id,true);const f=h.calls.find(c=>c.path==='checkout/sessions').form;assert.equal(f.mode,'subscription');assert.equal(f['line_items[0][price_data][unit_amount]'],'39900');assert.equal(f['line_items[0][quantity]'],'1');assert.equal(f['line_items[0][price_data][recurring][interval]'],'year');assert.equal(f['subscription_data[metadata][school_id]'],id);assert.equal(f['subscription_data[metadata][plan]'],SCHOOL_PLAN.id)});
test('Repeated open checkout reuses session; concurrent checkout is locked',async()=>{const h=harness(),id=await h.setup();const results=await Promise.allSettled([h.service.checkout(director,id,true),h.service.checkout(director,id,true)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.status,409);await h.service.checkout(director,id,true);assert.equal(h.calls.filter(c=>c.path==='checkout/sessions').length,1)});
test('Lost checkout response retries same idempotency key',async()=>{const h=harness(),id=await h.setup();await h.service.checkout(director,id,true);h.sql.prepare('UPDATE school_checkouts SET session_id=NULL WHERE school_id=?').run(id);await h.service.checkout(director,id,true);const calls=h.calls.filter(c=>c.path==='checkout/sessions');assert.equal(calls.length,2);assert.equal(calls[0].key,calls[1].key)});
test('Ambiguous checkout beyond idempotency retention blocks duplicate purchase',async()=>{const h=harness(),id=await h.setup();await h.service.checkout(director,id,true);h.sql.prepare('UPDATE school_checkouts SET session_id=NULL WHERE school_id=?').run(id);h.advance(24*3600000);await assert.rejects(h.service.checkout(director,id,true),e=>e.status===409);assert.equal(h.calls.filter(c=>c.path==='checkout/sessions').length,1)});
test('Expired checkout can start a new attempt',async()=>{const h=harness(),id=await h.setup();await h.service.checkout(director,id,true);h.session.status='expired';await h.service.checkout(director,id,true);const calls=h.calls.filter(c=>c.path==='checkout/sessions');assert.notEqual(calls[0].key,calls[1].key)});
test('Unpaid checkout does not grant access',async()=>{const h=harness(),id=await h.setup();await h.service.checkout(director,id,true);h.session.status='complete';h.session.subscription='sub_test';assert.equal((await h.service.confirm(director,h.session.id)).status,'pending');assert.equal((await h.service.view(director)).schools[0].access,false)});
test('Real Basil-shaped paid invoice without paid boolean grants test school access',async()=>{const h=harness(),id=await h.setup();await h.paid(id);assert.equal('paid' in h.sub.latest_invoice,false);assert.equal(schoolAccess(h.row(id),h.time),true);assert.equal((await h.service.view(director)).schools[0].access,true)});
test('Forged/other-user checkout return cannot grant access',async()=>{const h=harness(),id=await h.setup();await h.service.checkout(director,id,true);await assert.rejects(h.service.confirm(other,h.session.id),e=>e.status===404);await assert.rejects(h.service.confirm(director,'cs_live_fake'));await assert.rejects(h.service.confirm(director,'cs_test_unknown'),e=>e.status===404)});
test('Paid access never comes from incomplete, trialing, paused, past_due, unpaid or canceled status',async()=>{const h=harness(),id=await h.setup();await h.paid(id);for(const status of ['incomplete','trialing','paused','past_due','unpaid','canceled','incomplete_expired']){h.sub.status=status;await h.sync(id);assert.equal(schoolAccess(h.row(id),h.time),false,status)}});
test('Subscription cancel-at-end preserves paid access; expiry removes it',async()=>{const h=harness(),id=await h.setup();await h.paid(id);h.sub.cancel_at_period_end=true;await h.sync(id);assert.equal(h.row(id).cancel_at_end,1);assert.equal(schoolAccess(h.row(id),h.time),true);h.advance(366*86400000);await h.sync(id);assert.equal(schoolAccess(h.row(id),h.time),false)});
test('Cancel reversal preserves access and clears scheduled cancellation',async()=>{const h=harness(),id=await h.setup();await h.paid(id);h.sub.cancel_at_period_end=true;await h.sync(id);h.sub.cancel_at_period_end=false;await h.sync(id);assert.equal(h.row(id).cancel_at_end,0);assert.equal(schoolAccess(h.row(id),h.time),true)});
test('Paid renewal extends access; failed invoice never extends it',async()=>{const h=harness(),id=await h.setup();await h.paid(id);const previous=h.row(id).paid_until,item=h.sub.items.data[0],invoice=h.sub.latest_invoice;item.current_period_start=item.current_period_end;item.current_period_end+=365*86400;invoice.lines.data[0].period={start:item.current_period_start,end:item.current_period_end};invoice.status='open';invoice.amount_paid=0;invoice.amount_remaining=39900;await h.sync(id);assert.equal(h.row(id).paid_until,previous);h.advance(366*86400000);await h.sync(id);assert.equal(schoolAccess(h.row(id),h.time),false);invoice.status='paid';invoice.amount_paid=39900;invoice.amount_remaining=0;await h.sync(id);assert.ok(h.row(id).paid_until>previous);assert.equal(schoolAccess(h.row(id),h.time),true)});
test('Subscription plan, currency, amount, quantity, owner and live-mode mismatches rejected',async()=>{const h=harness(),id=await h.setup();await h.paid(id);for(const mutate of [s=>s.livemode=true,s=>s.customer='cus_other',s=>s.metadata.school_id='other',s=>s.metadata.plan='other',s=>s.items.data[0].quantity=2,s=>s.items.data[0].price.unit_amount=1,s=>s.items.data[0].price.currency='eur',s=>s.items.data[0].price.recurring.interval='month',s=>s.items.data[0].price.recurring.interval_count=2,s=>s.items.data.push(s.items.data[0])]){const sub=structuredClone(h.sub);mutate(sub);assert.throws(()=>validateSubscription(sub,h.row(id)))}});
test('Foreign, underpaid, partial, tax, discount and mismatched invoice lines cannot extend access',async()=>{const h=harness(),id=await h.setup();await h.paid(id);for(const mutate of [i=>i.amount_remaining=1,i=>i.amount_paid=1,i=>i.total=40000,i=>i.livemode=true,i=>i.customer='cus_other',i=>i.parent.subscription_details.subscription='sub_other',i=>i.lines.has_more=true,i=>i.lines.data[0].pricing.price_details.price='price_other',i=>i.lines.data[0].period.end++,i=>i.status='uncollectible']){const sub=structuredClone(h.sub);mutate(sub.latest_invoice);assert.equal(paidThrough(sub,sub.items.data[0]),0)}});
test('Existing active/past_due subscription prevents duplicate recurring charge',async()=>{const h=harness(),id=await h.setup();await h.paid(id);for(const status of ['active','past_due','unpaid','incomplete']){h.sub.status=status;await assert.rejects(h.service.checkout(director,id,true),e=>e.status===409)}assert.equal(h.calls.filter(c=>c.path==='checkout/sessions').length,1)});
test('Portal uses server-owned customer, invoices and cancel-at-period-end configuration',async()=>{const h=harness(),id=await h.setup();await assert.rejects(h.service.portal(director,id),e=>e.status===409);await h.paid(id);await h.service.portal(director,id);const config=h.calls.find(c=>c.path==='billing_portal/configurations').form;assert.equal(config['features[subscription_cancel][mode]'],'at_period_end');assert.equal(config['features[subscription_update][enabled]'],'false');assert.equal(h.calls.find(c=>c.path==='billing_portal/sessions').form.customer,h.row(id).customer_id)});
test('Invitation token is hashed, hidden from list and accepts only one facilitator',async()=>{const h=harness(),id=await h.setup(),inv=await h.service.invite(director,id);assert.notEqual(h.sql.prepare('SELECT token_hash FROM school_invites').get().token_hash,inv.token);assert.equal(JSON.stringify(await h.service.view(director)).includes(inv.token),false);await h.service.accept(teacher,inv.token);await h.service.accept(teacher,inv.token);await assert.rejects(h.service.accept(other,inv.token),e=>e.status===410);assert.equal((await h.service.view(director)).schools[0].members.length,2)});
test('Expired, revoked, unknown and malformed invitation rejected',async()=>{const h=harness(),id=await h.setup();const revoked=await h.service.invite(director,id);await h.service.revoke(director,id,revoked.id);await assert.rejects(h.service.accept(teacher,revoked.token),e=>e.status===410);const expired=await h.service.invite(director,id);h.advance(8*86400000);await assert.rejects(h.service.accept(teacher,expired.token),e=>e.status===410);await assert.rejects(h.service.accept(teacher,'f'.repeat(64)),e=>e.status===404);await assert.rejects(h.service.accept(teacher,'bad'),e=>e.status===400)});
test('Removed facilitator loses school membership and cannot replay consumed invitation',async()=>{const h=harness(),id=await h.setup();await h.paid(id);const inv=await h.service.invite(director,id);await h.service.accept(teacher,inv.token);assert.equal((await h.service.view(teacher)).schools[0].access,true);await h.service.remove(director,id,teacher.userId);assert.deepEqual((await h.service.view(teacher)).schools,[]);await assert.rejects(h.service.accept(teacher,inv.token),e=>e.status===410);await assert.rejects(h.service.remove(director,id,director.userId))});
test('Facilitator cannot see roster, unused links or unrelated school data',async()=>{const h=harness(),id=await h.setup(),inv=await h.service.invite(director,id);await h.service.accept(teacher,inv.token);const view=await h.service.view(teacher);assert.equal(view.schools[0].role,'facilitator');assert.deepEqual(view.schools[0].members,[]);assert.deepEqual(view.schools[0].invites,[]);assert.deepEqual((await h.service.view(other)).schools,[])});
test('Director cannot accidentally consume own invitation',async()=>{const h=harness(),id=await h.setup(),inv=await h.service.invite(director,id);await assert.rejects(h.service.accept(director,inv.token),e=>e.status===409);await h.service.accept(teacher,inv.token)});
test('Invite creation rate limit enforced',async()=>{const h=harness(),id=await h.setup();for(let i=0;i<20;i++)await h.service.invite(director,id);await assert.rejects(h.service.invite(director,id),e=>e.status===429)});
test('Concurrent invitation claims yield one member; losing claim cannot retry',async()=>{const h=harness(),id=await h.setup(),inv=await h.service.invite(director,id);const results=await Promise.allSettled([h.service.accept(teacher,inv.token),h.service.accept(other,inv.token)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await h.service.view(director)).schools[0].members.length,2)});
test('Stale cached access fails closed on Stripe outage',async()=>{const h=harness(),id=await h.setup();await h.paid(id);h.advance(61000);h.hook(()=>{throw new Error('Stripe unavailable')});assert.equal((await h.service.view(director)).schools[0].access,false);assert.equal((await h.service.view(director)).schools[0].access,true)});
test('Duplicate and out-of-order webhooks reconcile current Stripe status',async()=>{const h=harness(),id=await h.setup();await h.paid(id);h.sub.status='canceled';const event={type:'customer.subscription.updated',data:{object:{...structuredClone(h.sub),status:'active'}}};await h.service.webhook(event);await h.service.webhook(event);assert.equal(h.row(id).status,'canceled');assert.equal(schoolAccess(h.row(id),h.time),false)});
test('Unknown school/account events are ignored',async()=>{const h=harness();assert.equal(await h.service.webhook({type:'invoice.paid',data:{object:{customer:'cus_foreign',parent:{subscription_details:{subscription:'sub_foreign'}}}}}),true);assert.equal(await h.service.webhook({type:'checkout.session.completed',data:{object:{mode:'subscription',metadata:{school_id:'foreign'}}}}),true);assert.equal(h.calls.length,0)});
test('Invoice webhook before return binds known attempt and grants verified access',async()=>{const h=harness(),id=await h.setup();await h.paid(id);h.sql.prepare("UPDATE schools SET subscription_id=NULL,status='none',paid_until=0,synced_at=0 WHERE id=?").run(id);await h.service.webhook({type:'invoice.paid',data:{object:h.sub.latest_invoice}});assert.equal(schoolAccess(h.row(id),h.time),true)});
test('Lease expiry fences stale Stripe response from overwriting current status',async()=>{const h=harness(),id=await h.setup();await h.paid(id);let release;const pause=new Promise(resolve=>release=resolve);let reached;const entered=new Promise(resolve=>reached=resolve);h.hook(async()=>{reached();await pause});const old=h.sync(id);await entered;h.advance(121000);h.sub.status='canceled';await h.sync(id);release();await assert.rejects(old,e=>e.status===409);assert.equal(h.row(id).status,'canceled');assert.equal(h.sql.prepare('SELECT count(*) AS n FROM school_locks').get().n,0)});
