import test from 'node:test';
import assert from 'node:assert/strict';
import {harness,creator,admin,outsider,draft} from './feature-fixture.mjs';
import {storageVideo,VIDEO_PART_SIZE} from '../lib/storage-video.mjs';
import {inspectMp4,videoRange} from '../lib/mp4.mjs';
import {digest} from '../lib/content.mjs';
const box=(type,...data)=>{const body=Buffer.concat(data),b=Buffer.alloc(body.length+8);b.writeUInt32BE(b.length);b.write(type,4);body.copy(b,8);return b;};
function mp4(size=1024){const mvhd=Buffer.alloc(100);mvhd.writeUInt32BE(1000,12);mvhd.writeUInt32BE(12000,16);const visual=Buffer.alloc(78);visual.writeUInt16BE(640,24);visual.writeUInt16BE(360,26);const stsd=Buffer.alloc(8);stsd.writeUInt32BE(1,4);const header=Buffer.concat([box('ftyp',Buffer.from('isom\0\0\0\0isom')),box('moov',box('mvhd',mvhd),box('trak',box('mdia',box('minf',box('stbl',box('stsd',stsd,box('avc1',visual,box('avcC',Buffer.from([1,66,0,30,255,225,0,2,103,1,1,0,2,104,1])))))))))]),mdat=box('mdat',Buffer.alloc(size-header.length-8));return Buffer.concat([header,mdat]);}
async function setup(size=1024){const h=harness();await h.setupCreator();let c=await h.content.create(creator,crypto.randomUUID());c=await h.content.save(creator,c.id,c.revision,draft());const objects=new Map(),uploads=new Map(),hooks={};let next=0;const bucket={async createMultipartUpload(key,meta){const id=String(++next),parts=new Map();const handle={uploadId:id,async uploadPart(n,bytes){await hooks.part?.(n,bytes);const etag=await digest(bytes);parts.set(n,{bytes:Buffer.from(bytes),etag});return {partNumber:n,etag}},async complete(list){await hooks.complete?.();const body=Buffer.concat(list.map(p=>{const b=parts.get(p.partNumber);assert.equal(b.etag,p.etag);return b.bytes}));const o={size:body.length,customMetadata:meta.customMetadata,body};objects.set(key,o);return o},async abort(){uploads.delete(id)}};uploads.set(id,handle);await hooks.create?.();return handle},resumeMultipartUpload(key,id){const u=uploads.get(id);if(!u)throw new Error('Multipart not found');return u},async head(key){return objects.get(key)??null},async delete(key){await hooks.delete?.();objects.delete(key)}};
 const service=storageVideo({db:h.db,bucket,content:h.content,now:()=>h.time}),bytes=mp4(size),body={courseId:c.id,kind:'video',language:'en',lesson:0,name:'qa.mp4',size,fingerprint:await digest(bytes.subarray(0,VIDEO_PART_SIZE)),key:crypto.randomUUID()};return {...h,service,bucket,objects,uploads,hooks,c,body,bytes};}
async function send(h,id){for(let n=1;n<=Math.ceil(h.bytes.length/VIDEO_PART_SIZE);n++)await h.service.part(creator,id,n,h.bytes.subarray((n-1)*VIDEO_PART_SIZE,n*VIDEO_PART_SIZE));}
test('Private multipart upload is resumable and completion attaches one ready asset atomically',async()=>{const h=await setup(VIDEO_PART_SIZE+1024),s=await h.service.start(creator,h.body);await h.service.part(creator,s.id,1,h.bytes.subarray(0,VIDEO_PART_SIZE));const resumed=await h.service.start(creator,h.body);assert.deepEqual(resumed.received,[1]);assert.equal(resumed.hashes[1],h.body.fingerprint);await send(h,s.id);await h.service.complete(creator,s.id);await h.service.complete(creator,s.id);assert.equal(h.sql.prepare('SELECT count(*) n FROM content_assets').get().n,1);assert.equal((await h.content.detail(creator,h.c.id)).revision,h.c.revision+1);assert.equal((await h.service.status(creator,s.id)).status,'complete');});
test('Invalid kind, extension, size, fingerprint and missing lesson cannot start uploads',async()=>{const h=await setup();for(const change of [{kind:'plan'},{name:'x.exe'},{size:0},{size:2*1024**3+1},{size:1.5},{fingerprint:'bad'},{lesson:99}])await assert.rejects(h.service.start(creator,{...h.body,...change}));assert.equal(h.uploads.size,0)});
test('Foreign users and revoked creators cannot resume or read upload status',async()=>{const h=await setup(),s=await h.service.start(creator,h.body);await assert.rejects(h.service.status(outsider,s.id),e=>e.status===404);await h.content.grant(admin,creator.userId,'reader');await assert.rejects(h.service.part(creator,s.id,1,h.bytes),e=>e.status===403)});
test('Changed metadata or uploaded chunk bytes rejected; incomplete and incorrect chunks cannot complete',async()=>{const h=await setup(VIDEO_PART_SIZE+1024),s=await h.service.start(creator,h.body);await assert.rejects(h.service.start(creator,{...h.body,language:'es'}),e=>e.status===409);await assert.rejects(h.service.complete(creator,s.id),e=>e.status===409);for(const n of [0,4,1.5])await assert.rejects(h.service.part(creator,s.id,n,h.bytes));await assert.rejects(h.service.part(creator,s.id,1,h.bytes.subarray(0,5)));await h.service.part(creator,s.id,1,h.bytes.subarray(0,VIDEO_PART_SIZE));const changed=Buffer.from(h.bytes.subarray(0,VIDEO_PART_SIZE));changed[changed.length-1]=7;await assert.rejects(h.service.part(creator,s.id,1,changed),e=>e.status===409)});
test('Cancel discards object, cannot resurrect via start, and retries failed cleanup',async()=>{const h=await setup(),s=await h.service.start(creator,h.body);h.hooks.delete=()=>{throw new Error('temporary provider failure')};await assert.rejects(h.service.cancel(creator,s.id));h.hooks.delete=null;await h.service.cancel(creator,s.id);await assert.rejects(h.service.start(creator,h.body),e=>e.status===410);await assert.rejects(h.service.part(creator,s.id,1,h.bytes),e=>e.status===409)});
test('Cancel during provider setup prevents late create from resurrecting the session',async()=>{const h=await setup();h.hooks.create=async()=>{const r=h.sql.prepare('SELECT id FROM media_uploads').get();await h.service.cancel(creator,r.id)};await assert.rejects(h.service.start(creator,h.body));assert.equal(h.sql.prepare('SELECT status FROM media_uploads').get().status,'canceled');assert.equal(h.uploads.size,0)});
test('Provider-completed object recovers after lease timeout without duplicate asset',async()=>{const h=await setup(),s=await h.service.start(creator,h.body);await send(h,s.id);h.hooks.complete=()=>h.advance(120001);await assert.rejects(h.service.complete(creator,s.id),e=>e.status===409);assert.equal(h.objects.size,1);assert.equal(h.sql.prepare('SELECT count(*) n FROM content_assets').get().n,0);h.hooks.complete=null;await h.service.complete(creator,s.id);assert.equal(h.sql.prepare('SELECT count(*) n FROM content_assets').get().n,1)});
test('Reserved part bytes are immutable after an expired lease; identical retry recovers',async()=>{const h=await setup(),s=await h.service.start(creator,h.body);h.hooks.part=()=>h.advance(120001);await assert.rejects(h.service.part(creator,s.id,1,h.bytes),e=>e.status===409);assert.deepEqual((await h.service.status(creator,s.id)).received,[]);const changed=Buffer.from(h.bytes);changed[changed.length-1]=1;await assert.rejects(h.service.part(creator,s.id,1,changed),e=>e.status===409);h.hooks.part=null;await h.service.part(creator,s.id,1,h.bytes);await h.service.complete(creator,s.id)});
test('Concurrent draft edits prevent stale attachment and allow cleanup',async()=>{const h=await setup(),s=await h.service.start(creator,h.body);await send(h,s.id);await h.content.save(creator,h.c.id,h.c.revision,{...draft(),title:'Changed'});await assert.rejects(h.service.complete(creator,s.id),e=>e.status===409);assert.equal(h.sql.prepare('SELECT count(*) n FROM content_assets').get().n,0);await h.service.cancel(creator,s.id);assert.equal(h.objects.size,0)});
test('Completed upload cannot be canceled or removed through upload cancellation',async()=>{const h=await setup(),s=await h.service.start(creator,h.body);await send(h,s.id);await h.service.complete(creator,s.id);await assert.rejects(h.service.cancel(creator,s.id),e=>e.status===409);h.advance(7*86400000);assert.equal((await h.service.start(creator,h.body)).status,'complete');await h.content.remove(creator,s.id);await assert.rejects(h.service.start(creator,h.body),e=>e.status===410)});
test('Expired and stuck setup sessions give actionable failures',async()=>{const h=await setup(),s=await h.service.start(creator,h.body);h.sql.prepare("UPDATE media_uploads SET status='starting' WHERE id=?").run(s.id);await assert.rejects(h.service.start(creator,h.body),e=>e.status===409);h.advance(120001);await assert.rejects(h.service.start(creator,h.body),e=>e.status===410);h.sql.prepare("UPDATE media_uploads SET status='uploading' WHERE id=?").run(s.id);h.advance(7*86400000);await assert.rejects(h.service.start(creator,h.body),e=>e.status===410)});
test('MP4 validation rejects arbitrary, truncated, missing media and unsupported codec metadata',()=>{const good=mp4();assert.equal(inspectMp4(good).duration,12);for(const bytes of [Buffer.from('this is not video'),good.subarray(0,90),good.subarray(0,good.indexOf('mdat')-4)])assert.throws(()=>inspectMp4(bytes));for(const edit of [b=>b.write('hvc1',b.indexOf('avc1')),b=>b.writeUInt32BE(0,b.indexOf('stsd')+8),b=>b.write('xxxx',b.indexOf('avcC')),b=>{b.write('junk',8);b.write('junk',16)}]){const b=Buffer.from(good);edit(b);assert.throws(()=>inspectMp4(b));}});
test('Byte ranges cover seek/suffix/clamp and reject malformed or unsatisfiable requests',()=>{assert.equal(videoRange(null,100),null);assert.deepEqual(videoRange('bytes=10-19',100),{offset:10,length:10});assert.deepEqual(videoRange('bytes=90-',100),{offset:90,length:10});assert.deepEqual(videoRange('bytes=-12',100),{offset:88,length:12});assert.deepEqual(videoRange('bytes=90-999',100),{offset:90,length:10});for(const s of ['bytes=100-','bytes=10-1','bytes=-0','bytes=-','bytes=0-1,3-4','items=0-3','bytes=9007199254740999-'])assert.throws(()=>videoRange(s,100),e=>e.status===416)});
