'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useAccount} from './account';
import {Users,CheckCircle,ExternalLink,Copy,Trash2} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';

type School={id:string;name:string;role:string;status:string;access:boolean;paidUntil:number;periodEnd:number;cancelAtEnd:boolean;syncUnavailable:boolean;hasCustomer:boolean;members:{id:string;name:string;role:string}[];invites:{id:string;expiresAt:number}[]};
const date=(value:number)=>value?new Date(value).toLocaleDateString(): 'Not started';
export default function SchoolPage(){
 const a=useAccount(),[schools,setSchools]=useState<School[]>([]),[ready,setReady]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[name,setName]=useState(''),[consent,setConsent]=useState(false),[invite,setInvite]=useState<{school:string;url:string}|null>(null),[join,setJoin]=useState(''),[returnSession,setReturnSession]=useState(''),[remove,setRemove]=useState(''),started=useRef(false);
 const load=useCallback(async()=>{const response=await fetch('/api/schools',{cache:'no-store'}),data:any=await response.json();if(!response.ok)throw new Error(data.error);setSchools(data.schools);setReady(data.ready);},[]);
 useEffect(()=>{if(!a.data)return;void load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[a.data,load]);
 useEffect(()=>{const params=new URLSearchParams(location.search);setReturnSession(params.get('session_id')??'');if(params.has('canceled'))setMessage('Checkout was canceled. No school access was added.');const token=new URLSearchParams(location.hash.slice(1)).get('invite');if(token){setJoin(token);history.replaceState(null,'','/school');}},[]);
 const act=useCallback(async(label:string,action:string,data:unknown)=>{setBusy(label);setError('');setMessage('');try{const result=await a.post(action,data);await load();return result}catch(e){setError((e as Error).message);return null}finally{setBusy('')}},[a,load]);
 async function confirmReturn(){const result=await act('confirm','school-confirm',{sessionId:returnSession});if(result){setMessage(result.status==='active'?'Your test subscription has been confirmed.':'Payment is still pending. Retry confirmation after completing payment.');if(result.status==='active'){setReturnSession('');history.replaceState(null,'','/school');}}}
 useEffect(()=>{if(!a.data||started.current)return;started.current=true;const params=new URLSearchParams(location.search);if(params.has('session_id')){void (async()=>{setBusy('confirm');try{const result=await a.post('school-confirm',{sessionId:params.get('session_id')});await load();setMessage(result.status==='active'?'Test subscription confirmed.':'Payment is pending. Use Check payment again shortly.');if(result.status==='active'){setReturnSession('');history.replaceState(null,'','/school');}}catch(e){setError((e as Error).message)}finally{setBusy('')}})();}else if(params.has('billing_return')){void(async()=>{setBusy('refresh');try{const response=await fetch('/api/schools'),data:any=await response.json();if(!response.ok)throw new Error(data.error);for(const s of data.schools.filter((s:School)=>s.role==='director'))await a.post('school-refresh',{schoolId:s.id});await load();setMessage('Billing status refreshed.');}catch(e){setError((e as Error).message)}finally{setBusy('')}})();}},[a,load]);
 async function redirect(s:School,portal=false){const result=await act(s.id,portal?'school-portal':'school-checkout',{schoolId:s.id,consent});if(!result)return;if(!result.url){setMessage('Subscription status: '+result.status+'. Refresh billing if payment is still pending.');return;}try{const url=new URL(result.url),expected=portal?'billing.stripe.com':'checkout.stripe.com';if(url.protocol!=='https:'||url.hostname!==expected)throw new Error('Unexpected billing destination.');location.assign(url.href);}catch(e){setError((e as Error).message)}}
 async function createInvite(s:School){const result=await act('invite-'+s.id,'school-invite',{schoolId:s.id});if(result)setInvite({school:s.id,url:location.origin+'/school#invite='+result.token});}
 if(!a.data)return null;
 return <div className="school-workspace">
  <div className="school-intro"><div><span className="badge">TEST SUBSCRIPTIONS</span><h2>School & billing</h2><p><strong>$399 / year per physical location.</strong> All curriculum and unlimited adult facilitators. Renews annually until canceled.</p></div><Users size={42}/></div>
  <p className="fine-print">Provisional pricing. This prototype uses sample curriculum and Stripe test cards only. No live charges or production license is issued.</p>
  {!ready&&<div className="school-notice">Stripe is not connected yet. You can create your school and manage facilitators now. Subscription checkout and billing management become available after Stripe test setup.</div>}
  {error&&<p className="error school-notice" role="alert">{error} <button className="underlined" onClick={()=>void load().then(()=>setError('')).catch(e=>setError(e.message))}>Reload schools</button></p>}
  {message&&<p className="school-notice" role="status"><CheckCircle size={18}/> {message}</p>}
  {returnSession&&<button className="button secondary" disabled={!!busy} onClick={()=>void confirmReturn()}>Check payment</button>}
  {join&&<div className="status-panel"><h3>Join as a facilitator</h3><p>A school director shared this single-use invitation. Joining shares your account display name with that director. Only join a school you recognize.</p><div className="button-row"><button className="button primary" disabled={!!busy} onClick={()=>void act('join','school-join',{token:join}).then(result=>{if(result){setJoin('');setMessage('You joined the school. Curriculum access follows its subscription.');}})}>Accept school invitation</button><button className="button secondary" onClick={()=>setJoin('')}>Dismiss</button></div></div>}
  {loading?<p role="status">Loading schools…</p>:<>
   {!schools.some(s=>s.role==='director')&&<form className="request-form school-create" onSubmit={e=>{e.preventDefault();void act('create','school-create',{name}).then(result=>{if(result)setName('')})}}><h3>Create your school</h3><label>School or physical location name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={120} placeholder="For example, Riverside STEM Club"/></label><button className="button primary" disabled={!!busy}>{busy==='create'?'Creating…':'Create school'}</button><p className="fine-print">One director-managed physical location per account in this version. Multi-site networks can request a custom quote.</p></form>}
   {schools.map(s=><section className="school-card" key={s.id}>
    <div className="school-card-head"><div><span className="eyebrow">{s.role}</span><h2>{s.name}</h2></div><span className="badge">{s.access?'Test access active':s.status==='none'?'No subscription':s.status.replaceAll('_',' ')}</span></div>
    <dl className="school-facts"><div><dt>Paid access through</dt><dd>{date(Math.min(s.paidUntil,s.periodEnd))}</dd></div><div><dt>{s.cancelAtEnd?'Scheduled cancellation':'Next renewal'}</dt><dd>{['active','past_due'].includes(s.status)?date(s.periodEnd):'Not scheduled'}</dd></div></dl>
    {s.syncUnavailable&&<p className="error">We could not verify current billing. School access is paused until it can be confirmed.</p>}
    {s.cancelAtEnd&&<p>Your subscription is scheduled to end on {date(s.periodEnd)}. Paid access remains until then. Use Manage billing to review it.</p>}
    {['past_due','unpaid','incomplete','paused'].includes(s.status)&&<p className="error">Payment needs attention. The director can update the payment method in Manage billing, then refresh this page.</p>}
    {s.role==='director'?<>
     {['none','canceled','incomplete_expired'].includes(s.status)&&<div className="school-subscribe"><div className="consent"><Checkbox id={'renew-'+s.id} checked={consent} onCheckedChange={value=>setConsent(value===true)}/><label htmlFor={'renew-'+s.id}>I authorize a $399 annual test subscription for this physical location, renewing each year until canceled. I will use test card details.</label></div><button className="button primary" disabled={!!busy||!ready||!consent} onClick={()=>void redirect(s)}>Start annual test subscription <ExternalLink size={16}/></button></div>}
     <div className="button-row school-buttons">{s.hasCustomer&&<button className="button secondary" disabled={!!busy||!ready} onClick={()=>void redirect(s,true)}>Manage billing & invoices <ExternalLink size={16}/></button>}<button className="button secondary" disabled={!!busy} onClick={()=>void act('refresh-'+s.id,'school-refresh',{schoolId:s.id}).then(r=>{if(r)setMessage('Billing status refreshed.')})}>Refresh billing status</button></div>
     <div className="school-team"><h3>Facilitators ({s.members.length})</h3><p>Give each adult their own sign-in and join link. Removing a facilitator immediately removes their school membership.</p><ul className="school-members">{s.members.map(m=><li key={m.id}><div><strong>{m.name}</strong><span>{m.role}</span></div>{m.role!=='director'&&(remove===m.id?<div className="button-row"><button className="button secondary" disabled={!!busy} onClick={()=>void act('remove-'+m.id,'school-remove',{schoolId:s.id,memberId:m.id}).then(r=>{if(r)setRemove('')})}>Confirm removal</button><button className="text-button" onClick={()=>setRemove('')}>Keep</button></div>:<button className="text-button" aria-label={'Remove '+m.name} disabled={!!busy} onClick={()=>setRemove(m.id)}><Trash2 size={17}/> Remove</button>)}</li>)}</ul>
      <button className="button secondary" disabled={!!busy} onClick={()=>void createInvite(s)}>Create facilitator join link</button>
      {invite?.school===s.id&&<div className="school-invite"><label>Single-use link · expires in 7 days<input aria-label="Facilitator join link" value={invite.url} readOnly onFocus={e=>e.target.select()}/></label><button className="button secondary" onClick={()=>void navigator.clipboard.writeText(invite.url).then(()=>setMessage('Join link copied. Share it with one adult facilitator.')).catch(()=>setError('Copy unavailable. Select and copy the link above.'))}><Copy size={16}/> Copy link</button></div>}
      <p className="fine-print">Links are shown once and are not emailed. While this website is private, invited facilitators also need permission to open the site. A join link does not change the website’s sharing settings.</p>
      {!!s.invites.length&&<details><summary>Unused invitations ({s.invites.length})</summary><ul className="school-members">{s.invites.map(i=><li key={i.id}><span>Expires {date(i.expiresAt)}</span><button className="text-button" disabled={!!busy} onClick={()=>void act('revoke-'+i.id,'school-revoke',{schoolId:s.id,inviteId:i.id}).then(r=>{if(r){setInvite(null);setMessage('Invitation revoked.')}})}>Revoke link</button></li>)}</ul></details>}
     </div>
    </>:<p>Your director manages this school’s billing and membership. {s.access?<a className="underlined" href="/library">Open your curriculum.</a>:'Ask your director about subscription access.'}</p>}
   </section>)}
  </>}
 </div>;
}
