'use client';
import {useState,lazy,Suspense} from 'react';
import {ArrowUpRight,ArrowRight,Play,ShoppingBag,BookOpen,Sprout,Orbit,Zap,Bot,Code2,Menu,X,Check} from 'lucide-react';
import {subjects,products,money,heroImage,sampleVideo,sampleSource,Product} from '@/lib/catalog';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AccountProvider,useAccount} from './account';
import {Streams,AudienceCards} from './resources';
const SecureVideo=lazy(()=>import('./teaching').then(m=>({default:m.SecureVideo})));
const Views=lazy(()=>import('./views'));
const icons={Sprout,Orbit,Zap,Bot,Code2};
export default function Site({path}:{path:string[]}){
 return <AccountProvider><SiteBody path={path}/></AccountProvider>;
}
function SiteBody({path}:{path:string[]}){
 const account=useAccount(),products=account.products;
 const [video,setVideo]=useState(false),[menu,setMenu]=useState(false);
 return <><a className="skip" href="#main">Skip to content</a><div className="prototype-bar">A little preview of a big idea. <span>Sample curriculum & pricing · No real charges</span></div><header className="header"><a className="brand" href="/" aria-label="SwIRL home"><span className="brand-symbol">s</span><strong>SwIRL<span>STEM FOR EVERY CURIOUS MIND</span></strong></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation"><a href="/curriculum">Explore curriculum</a><a href="/solutions">For your program</a><a href="/pricing">Pricing</a><a href="/about">Our story</a></nav><div className="header-actions"><a className="portal-link" href="/library"><BookOpen size={18}/> My classroom</a><a className="cart-link" href="/cart" aria-label={"Shopping cart, "+(account.data?.cart.length??0)+" items"}><ShoppingBag size={21}/>{!!account.data?.cart.length&&<span className="cart-count">{account.data.cart.length}</span>}</a><button className="mobile-menu" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><main id="main">
 {path.length?<Suspense fallback={<div className="wrap page" role="status">Opening your workspace…</div>}><Views path={path} showVideo={()=>setVideo(true)}/></Suspense>:<><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span/> SMALL HANDS. BIG DISCOVERIES.</div><h1>Make room<br/>for <em>wonder.</em></h1><p>Hands-on STEM adventures that turn “what if?” into “I made this.” Ready-to-use digital curriculum for educators, programs, and curious families.</p><div className="button-row"><a className="button primary" href="/curriculum">Find your next discovery <ArrowUpRight size={19}/></a><button className="text-button" onClick={()=>setVideo(true)}><span className="play-circle"><Play size={13} fill="currentColor"/></span> See a sample activity</button></div><a className="text-link pilot-link" href="/request?kind=pilot">Request a pilot for your program →</a><div className="hero-note"><Check size={16}/> Digital lessons. Everyday materials. Extraordinary possibilities.</div></div><div className="hero-visual"><div className="photo-frame"><img fetchPriority="high" decoding="async" src={heroImage} alt="Paper helicopter templates, scissors, a pencil, and measuring tape laid out for a science activity"/><div className="photo-label"><span>THE NEXT BIG IDEA</span><strong>Starts with a little tinkering.</strong><button aria-label="Play sample activity" onClick={()=>setVideo(true)}><Play size={22} fill="currentColor"/></button></div></div><span className="photo-credit">Activity image courtesy NASA/JPL-Caltech</span><div className="floating-note"><Orbit size={24}/><div><b>Learn it. Build it. Try again.</b><span>That’s the SwIRL spirit.</span></div></div></div></section>
 <section className="promise-strip"><div><BookOpen/> Everything delivered digitally</div><div><BookOpen/> Made for grown-ups who teach</div><div><Sprout/> Built around hands-on discovery</div></section>
 <section className="subjects-section wrap"><div className="section-heading"><div><div className="eyebrow">FOLLOW THEIR CURIOSITY</div><h2>A whole world of <em>why.</em></h2></div><p>Five ways to spark a new interest.<br/>Endless places it can take them.</p></div><div className="subject-grid">{subjects.map((s,i)=>{const Icon=icons[s.icon];return <a className="subject-card" key={s.id} href={'/curriculum/'+s.id} style={{'--tile':s.color} as React.CSSProperties}><span className="subject-number">0{i+1}</span><Icon size={39} strokeWidth={1.4}/><h3>{s.name}</h3><p>{s.short}</p><ArrowUpRight className="subject-arrow" size={20}/></a>})}</div></section>
 <Streams/><AudienceCards/><section className="featured wrap"><div className="section-heading"><div><div className="eyebrow">GOOD PLACES TO START</div><h2>Small projects. <em>Big aha’s.</em></h2></div><a className="text-link" href="/curriculum">Explore all curriculum <ArrowRight size={18}/></a></div><div className="product-grid">{products.slice(0,3).map(p=><ProductCard key={p.id} p={p}/>)}</div></section>
 <section className="mission wrap"><div><div className="eyebrow">CURIOUS MINDS BELONG EVERYWHERE</div><h2>For the classroom.<br/>The kitchen table.<br/><em>And everything in between.</em></h2></div><div><p>SwIRL brings science and engineering within reach. Our digital resources help parents, tutors, and program leaders make space for meaningful, hands-on learning.</p><a className="button primary" href="/solutions">Find your fit <ArrowUpRight size={18}/></a></div></section></>}
 {account.site.partners&&<section className="wrap approved-claims"><h3>Program partners</h3><p className="preserve-lines">{account.site.partners}</p></section>}{!!account.site.logos?.length&&<section className="wrap partner-logos" aria-label="Approved program partners">{account.site.logos.map((l:any)=><img loading="lazy" decoding="async" key={l.id} src={'/api/public-logo?id='+l.id} alt={l.name}/>)}</section>}{account.site.impactCount>0&&<section className="wrap impact-counter"><strong>{account.site.impactCount.toLocaleString()}</strong><span>{account.site.impactLabel}</span></section>}{account.site.impact&&<section className="wrap approved-claims"><p>{account.site.impact}</p></section>}</main><footer className="footer"><div className="wrap footer-top"><a className="brand" href="/"><span className="brand-symbol">s</span><strong>SwIRL<span>LET CURIOSITY TAKE THE LEAD.</span></strong></a><p>Southwest Innovation Research Lab<br/>College Station, Texas</p><div><a href="/about">About SwIRL</a><a href="/school">School & billing</a><a href="/studio">Curriculum studio</a><a href="/marketing">Marketing hub</a><a href="/sample">Free sample</a><a href="/terms">Draft terms</a><a href="/help">Help & digital access</a><a href="/privacy">Privacy</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} SwIRL. A curriculum store prototype.</span><span>Digital resources only. Materials and kits sold separately.</span></div></footer><Dialog open={video} onOpenChange={setVideo}><DialogContent className="video-dialog"><DialogHeader><DialogTitle>One small build. A big discovery.</DialogTitle><DialogDescription>{account.site.introCourse?'Introduction uploaded by the SwIRL curriculum team.':'Public sample activity from NASA/JPL-Caltech. This is a placeholder for the SwIRL introduction video.'}</DialogDescription></DialogHeader>{account.site.introCourse?<Suspense fallback={<p>Loading video…</p>}><SecureVideo courseId={account.site.introCourse} assetId="" publicIntro/></Suspense>:<iframe title="NASA sample: Make a Paper Mars Helicopter" src={video?sampleVideo:undefined} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>}<a href={sampleSource} target="_blank" rel="noreferrer">View the original activity and instructions ↗</a></DialogContent></Dialog></>;
}
export function ProductCard({p}:{p:Product}){const subject=subjects.find(s=>s.id===p.subject)!;const Icon=icons[subject.icon];return <a className="product-card" href={'/course/'+p.id}><div className="product-art" style={{background:p.color}}>{p.coverAsset?<img loading="lazy" decoding="async" className="course-cover" src={'/api/public-image?id='+p.coverAsset} alt={p.title}/>:<Icon size={64} strokeWidth={1}/>}<span>{p.format}</span></div><div className="product-copy"><div className="eyebrow">{subject.name}</div><h3>{p.title}</h3><p>Ages {p.ages}<span>·</span>{p.minutes} min activities</p><div className="product-bottom"><strong>{money(p.price)}</strong><span>Explore <ArrowUpRight size={17}/></span></div></div></a>}
