'use client';
import {useEffect,useState,lazy,Suspense} from 'react';
import {ArrowUpRight,ArrowRight,Play,ShoppingBag,BookOpen,Sprout,Orbit,Zap,Bot,Code2,Menu,X,Check} from 'lucide-react';
import {subjects,money,heroImage,sampleVideo,sampleSource,Product} from '@/lib/catalog';
import {introPlaceholder} from '@/lib/placeholder-videos.mjs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AccountProvider,useAccount} from './account';
import {Streams,AudienceCards} from './resources';
import {PlaceholderVideo} from './placeholder-video';
import {initials} from './google-button';
const SecureVideo=lazy(()=>import('./teaching').then(m=>({default:m.SecureVideo})));
const Views=lazy(()=>import('./views'));
const icons={Sprout,Orbit,Zap,Bot,Code2};
const settings=['camps.','after-school.','early learning.','families.'];
export default function Site({path}:{path:string[]}){
 return <AccountProvider><SiteBody path={path}/></AccountProvider>;
}
function RotatingAudience(){const [i,setI]=useState(0);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setInterval(()=>setI(x=>(x+1)%settings.length),2600);return()=>clearInterval(timer)},[]);return <em className="rotating-word">{settings[i]}</em>}
function Metrics({products}:{products:Product[]}){const lessons=products.reduce((n,p)=>n+p.lessons.length,0),setup=Math.round(products.reduce((n,p)=>n+(p.setup??5),0)/Math.max(products.length,1));return <section className="metrics wrap" aria-label="Curriculum at a glance"><div><strong>{lessons}</strong><span>hands-on lessons & activities</span></div><div><strong>{subjects.length}</strong><span>STEM streams, ages 3–14</span></div><div><strong>Zero</strong><span>heavy hardware or lab required</span></div><div><strong>~{setup} min</strong><span>average setup time</span></div></section>}
function Intro(){const account=useAccount();return <section className="intro-section wrap" id="intro" aria-labelledby="intro-heading"><div><div className="eyebrow">MEET SWIRL IN ONE MINUTE</div><h2 id="intro-heading">How the curriculum <em>works.</em></h2><p>A SwIRL STEM tutor explains the curriculum and how a session runs, from choosing a stream to the final share-out.</p><ol className="intro-steps"><li><strong>Choose a stream</strong><span>Biology & chemistry, physics, electronics, robotics, or math & coding.</span></li><li><strong>Prep in about a minute</strong><span>Watch the counselor video and gather the supply list.</span></li><li><strong>Teach and discover</strong><span>Play the lesson video, hand out worksheets, and let learners build.</span></li></ol></div><div className="intro-player">{account.site.introCourse?<Suspense fallback={<p role="status">Loading video…</p>}><SecureVideo courseId={account.site.introCourse} assetId="" publicIntro/></Suspense>:<PlaceholderVideo video={introPlaceholder} src="/api/lesson-video?kind=intro" note="Introduction video"/>}</div></section>}
function SiteBody({path}:{path:string[]}){
 const account=useAccount(),products=account.products;
 const [video,setVideo]=useState(false),[menu,setMenu]=useState(false);
 return <><a className="skip" href="#main">Skip to content</a><div className="prototype-bar">Hands-on STEM for every curious mind. <span>Instant digital access · Supplies sourced separately</span></div><header className="header"><a className="brand" href="/" aria-label="SwIRL home"><span className="brand-symbol">s</span><strong>SwIRL<span>STEM FOR EVERY CURIOUS MIND</span></strong></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation"><a href="/curriculum">Explore curriculum</a><a href="/solutions">For your program</a><a href="/pricing">Pricing</a><a href="/about">Our story</a></nav><div className="header-actions">{!account.loading&&!account.data&&<a className="portal-link signin-link" href="/signin">Sign in</a>}{account.data&&<a className="portal-link account-link" href="/account" aria-label={'My profile, signed in as '+account.data.user.email}><span className="avatar" aria-hidden="true">{initials(account.data.user.name||account.data.user.email)}</span><span className="account-name">{(account.data.user.name||account.data.user.email).split(/[\s@]/)[0]}</span></a>}<a className="portal-link" href="/library"><BookOpen size={18}/> My classroom</a><a className="cart-link" href="/cart" aria-label={"Shopping cart, "+(account.data?.cart.length??0)+" items"}><ShoppingBag size={21}/>{!!account.data?.cart.length&&<span className="cart-count">{account.data.cart.length}</span>}</a><button className="mobile-menu" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><main id="main">
 {path.length?<Suspense fallback={<div className="wrap page" role="status">Opening your workspace…</div>}><Views path={path}/></Suspense>:<><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span/> SMALL HANDS. BIG DISCOVERIES.</div><h1 className="hero-title" aria-label="Zero-prep STEM curriculum built for camps, after-school, early learning, and families">Zero-prep STEM<br/>built for<br/><RotatingAudience/></h1><p>Hands-on science and engineering lessons with videos, printable plans, and everyday materials. Ready to teach in about five minutes, with no lab or heavy hardware required.</p><div className="button-row"><a className="button primary" href="/request?kind=pilot">Request a free pilot unit <ArrowUpRight size={19}/></a><a className="button secondary" href="/curriculum">Explore curriculum streams</a></div><a className="text-button intro-link" href="#intro"><span className="play-circle"><Play size={13} fill="currentColor"/></span> Watch the one-minute introduction</a><div className="hero-note"><Check size={16}/> Digital lessons. Everyday materials. Extraordinary possibilities.</div></div><div className="hero-visual"><div className="photo-frame"><img fetchPriority="high" decoding="async" src={heroImage} alt="Paper helicopter templates, scissors, a pencil, and measuring tape laid out for a science activity"/><div className="photo-label"><span>THE NEXT BIG IDEA</span><strong>Starts with a little tinkering.</strong><button aria-label="Play the paper helicopter sample activity" onClick={()=>setVideo(true)}><Play size={22} fill="currentColor"/></button></div></div><span className="photo-credit">Activity image courtesy NASA/JPL-Caltech</span><div className="floating-note"><Orbit size={24}/><div><b>Learn it. Build it. Try again.</b><span>That’s the SwIRL spirit.</span></div></div></div></section>
 <section className="promise-strip"><div><BookOpen/> Everything delivered digitally</div><div><BookOpen/> Made for grown-ups who teach</div><div><Sprout/> Built around hands-on discovery</div></section>
 <Intro/><Metrics products={products}/>
 <section className="subjects-section wrap"><div className="section-heading"><div><div className="eyebrow">FOLLOW THEIR CURIOSITY</div><h2>A whole world of <em>why.</em></h2></div><p>Five ways to spark a new interest.<br/>Endless places it can take them.</p></div><div className="subject-grid">{subjects.map((s,i)=>{const Icon=icons[s.icon];return <a className="subject-card" key={s.id} href={'/curriculum/'+s.id} style={{'--tile':s.color} as React.CSSProperties}><span className="subject-number">0{i+1}</span><Icon size={39} strokeWidth={1.4}/><h3>{s.name}</h3><p>{s.short}</p><ArrowUpRight className="subject-arrow" size={20}/></a>})}</div></section>
 <Streams/><AudienceCards/><section className="featured wrap"><div className="section-heading"><div><div className="eyebrow">GOOD PLACES TO START</div><h2>Small projects. <em>Big aha’s.</em></h2></div><a className="text-link" href="/curriculum">Explore all curriculum <ArrowRight size={18}/></a></div><div className="product-grid">{products.slice(0,3).map(p=><ProductCard key={p.id} p={p}/>)}</div></section>
 <section className="mission wrap"><div><div className="eyebrow">CURIOUS MINDS BELONG EVERYWHERE</div><h2>For the classroom.<br/>The kitchen table.<br/><em>And everything in between.</em></h2></div><div><p>SwIRL brings science and engineering within reach. Our digital resources help parents, tutors, and program leaders make space for meaningful, hands-on learning.</p><a className="button primary" href="/solutions">Find your fit <ArrowUpRight size={18}/></a></div></section></>}
 {account.site.partners&&<section className="wrap approved-claims"><h3>Program partners</h3><p className="preserve-lines">{account.site.partners}</p></section>}{!!account.site.logos?.length&&<section className="wrap partner-logos" aria-label="Approved program partners">{account.site.logos.map((l:any)=><img loading="lazy" decoding="async" key={l.id} src={'/api/public-logo?id='+l.id} alt={l.name}/>)}</section>}{account.site.impactCount>0&&<section className="wrap impact-counter"><strong>{account.site.impactCount.toLocaleString()}</strong><span>{account.site.impactLabel}</span></section>}{account.site.impact&&<section className="wrap approved-claims"><p>{account.site.impact}</p></section>}</main><footer className="footer"><div className="wrap footer-top"><a className="brand" href="/"><span className="brand-symbol">s</span><strong>SwIRL<span>LET CURIOSITY TAKE THE LEAD.</span></strong></a><p>Southwest Innovation Research Lab<br/>College Station, Texas</p><div><a href="/about">About SwIRL</a><a href="/school">School & billing</a><a href="/studio">Curriculum studio</a><a href="/marketing">Marketing hub</a><a href="/sample">Free sample</a><a href="/contact">Contact us</a><a href="/terms">Terms</a><a href="/help">Help & digital access</a><a href="/privacy">Privacy</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Southwest Innovation Research Lab (SwIRL).</span><span>Digital resources only. Materials and kits sold separately.</span></div></footer><Dialog open={video} onOpenChange={setVideo}><DialogContent className="video-dialog"><DialogHeader><DialogTitle>Make a paper Mars helicopter</DialogTitle><DialogDescription>The activity in our photo: a public sample activity from NASA/JPL-Caltech.</DialogDescription></DialogHeader><iframe title="NASA sample: Make a Paper Mars Helicopter" src={video?sampleVideo:undefined} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/><a href={sampleSource} target="_blank" rel="noreferrer">View the original activity and instructions ↗</a></DialogContent></Dialog></>;
}
export function ProductCard({p}:{p:Product}){const subject=subjects.find(s=>s.id===p.subject)!;const Icon=icons[subject.icon];return <a className="product-card" href={'/course/'+p.id}><div className="product-art" style={{background:p.color}}>{p.coverAsset?<img loading="lazy" decoding="async" className="course-cover" src={'/api/public-image?id='+p.coverAsset} alt={p.title}/>:<Icon size={64} strokeWidth={1}/>}<span>{p.format}</span></div><div className="product-copy"><div className="eyebrow">{subject.name}</div><h3>{p.title}</h3><p>Ages {p.ages}<span>·</span>{p.minutes} min activities{p.track==='week-camp'&&<><span>·</span>Week-long camp</>}</p><div className="product-bottom"><strong>{money(p.price)}</strong><span>Explore <ArrowUpRight size={17}/></span></div></div></a>}
