export const subjects = [
 {id:'biology', name:'Biology & chemistry', short:'Life gets interesting.', description:'Grow, mix, observe, and discover the science of living things.', icon:'Sprout', color:'#e2f3dd'},
 {id:'physics', name:'Physics & mechanics', short:'Big ideas. Small builds.', description:'Explore forces and motion with things you can find around you.', icon:'Orbit', color:'#e3eafd'},
 {id:'electronics', name:'Electronics', short:'Make a connection.', description:'Bring bright ideas to life with circuits, light, and simple logic.', icon:'Zap', color:'#fff0ba'},
 {id:'robotics', name:'Robotics', short:'Build. Program. Repeat.', description:'Turn curious makers into problem-solvers, one robot at a time.', icon:'Bot', color:'#fbe3d8'},
 {id:'coding', name:'Math & coding', short:'Think outside the blocks.', description:'Find patterns, solve puzzles, and turn ideas into algorithms.', icon:'Code2', color:'#eee3fa'},
] as const;
export type Product = {id:string; title:string; subject:string; ages:string; minutes:number; format:string; price:number; supply:string; description:string; materials:string[]; lessons:string[]; color:string};
export const products:Product[] = [
 {id:'wind-powered-car',title:'Build a wind-powered car',subject:'physics',ages:'6–10',minutes:45,format:'Complete course',price:2900,supply:'Low cost',description:'A little cardboard. A lot of possibility. Explore how a sail catches air, then build, test, and improve a moving invention.',materials:['Cardboard','Paper','Straws','Tape','Wooden skewers (adult use)','Bottle caps'],lessons:['Meet the challenge','How forces move things','Explore your materials','Sketch your design','Build the chassis','Add wheels and axles','Make a sail','Test and measure','Improve your design','Share your discovery'],color:'#e3eafd'},
 {id:'seed-to-sprout',title:'From seed to sprout',subject:'biology',ages:'3–5',minutes:30,format:'Lesson plan',price:900,supply:'Household',description:'Start a tiny garden and observe what plants need to grow. A playful introduction to asking questions and recording changes.',materials:['Seeds','Paper towels','Clear cups','Water'],lessons:['Meet a seed','Set up your garden','Observe and draw'],color:'#e2f3dd'},
 {id:'paper-circuits',title:'Light up a paper city',subject:'electronics',ages:'6–10',minutes:60,format:'Complete course',price:2900,supply:'Specialty kit',description:'Discover closed circuits while designing a city of glowing paper buildings. Adult handling of batteries is required.',materials:['Cardstock','Copper tape','LEDs','Enclosed AA battery holder'],lessons:['What is a circuit?','Meet the components','Build a safe circuit','Find the break','Make a switch','Sketch a city','Fold buildings','Add lights','Test the city','Share and reflect'],color:'#fff0ba'},
 {id:'robot-rescue',title:'Mission: robot rescue',subject:'robotics',ages:'11–14',minutes:60,format:'Complete course',price:3900,supply:'Specialty kit',description:'Plan a rescue route, program a robot, and learn why testing is part of every great invention. A compatible robot kit is required separately.',materials:['Programmable robot kit','Computer or tablet','Tape','Cardboard obstacles'],lessons:['The rescue mission','Meet your robot','Plan a route','Sequence commands','Test movement','Use loops','Explore sensors','Debug your route','Run the mission','Reflect and improve'],color:'#fbe3d8'},
 {id:'code-without-screens',title:'Coding without a screen',subject:'coding',ages:'6–10',minutes:30,format:'Workbook',price:1200,supply:'Household',description:'Become a human robot, write a sequence, and debug a maze with printable, unplugged coding challenges.',materials:['Paper','Pencils','Grid cards'],lessons:['Give clear instructions','Build a sequence','Debug a maze','Repeat with loops'],color:'#eee3fa'},
 {id:'kitchen-discoveries',title:'Kitchen science discoveries',subject:'biology',ages:'6–10',minutes:45,format:'Video lessons',price:1900,supply:'Household',description:'Investigate everyday changes through observation and simple experiments with an adult facilitator.',materials:['Clear cups','Water','Salt','Spoons','Paper towels'],lessons:['Ask a testable question','Compare materials','Observe a change','Record your findings','Explain your discovery'],color:'#e2f3dd'},
 {id:'bridge-builders',title:'The great bridge challenge',subject:'physics',ages:'11–14',minutes:60,format:'Lesson plan',price:900,supply:'Low cost',description:'Design a paper bridge, test its strength, and use evidence to make your next version even better.',materials:['Paper','Tape','Books','Small test weights'],lessons:['Explore structures','Design your bridge','Test and redesign'],color:'#e3eafd'},
 {id:'supply-planner',title:'Maker materials checklist',subject:'electronics',ages:'6–10',minutes:30,format:'Materials list',price:500,supply:'Low cost',description:'A printable checklist for setting up a small maker station, with facilitator preparation notes.',materials:['Printer','Pencil'],lessons:['Plan your maker station'],color:'#fff0ba'},
];
export const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(cents/100);
export const findProduct=(id:string)=>products.find(p=>p.id===id);
export const heroImage='https://d2pn8kiwq2w21t.cloudfront.net/images/paperhelicopter_materials.width-1320.jpg';
export const sampleVideo='https://www.youtube-nocookie.com/embed/HrKRWsrZuYc';
export const sampleSource='https://www.jpl.nasa.gov/edu/resources/project/make-a-paper-mars-helicopter-2/';
