export const subjects = [
 {id:'biology', name:'Biology & chemistry', short:'Life gets interesting.', description:'Grow, mix, observe, and discover the science of living things.', icon:'Sprout', color:'#e2f3dd'},
 {id:'physics', name:'Physics & mechanics', short:'Big ideas. Small builds.', description:'Explore forces and motion with things you can find around you.', icon:'Orbit', color:'#e3eafd'},
 {id:'electronics', name:'Electronics', short:'Make a connection.', description:'Bring bright ideas to life with circuits, light, and simple logic.', icon:'Zap', color:'#fff0ba'},
 {id:'robotics', name:'Robotics', short:'Build. Program. Repeat.', description:'Turn curious makers into problem-solvers, one robot at a time.', icon:'Bot', color:'#fbe3d8'},
 {id:'coding', name:'Math & coding', short:'Think outside the blocks.', description:'Find patterns, solve puzzles, and turn ideas into algorithms.', icon:'Code2', color:'#eee3fa'},
] as const;
export const formats=['Complete course','Video lessons','PDF Book','Workbook','Lesson plan','Materials list'] as const;
export type Product = {id:string; title:string; subject:string; ages:string; minutes:number; format:string; price:number; supply:string; description:string; materials:string[]; lessons:string[]; color:string;custom?:boolean;sample?:boolean;outcomes?:string;standards?:string;safety?:string;track?:string;coverAsset?:string;setup?:number;steps?:{title:string;instructions:string;prep:string;minutes:number}[]};
export const products:Product[] = [
 {id:'wind-powered-car',title:'Build a wind-powered car',subject:'physics',ages:'6–10',minutes:45,format:'Complete course',price:99,supply:'Low cost',setup:5,description:'A little cardboard. A lot of possibility. Explore how a sail catches air, then build, test, and improve a moving invention.',materials:['Cardboard','Paper','Straws','Tape','Wooden skewers (adult use)','Bottle caps'],lessons:['Meet the challenge','How forces move things','Explore your materials','Sketch your design','Build the chassis','Add wheels and axles','Make a sail','Test and measure','Improve your design','Share your discovery'],color:'#e3eafd'},
 {id:'seed-to-sprout',title:'From seed to sprout',subject:'biology',ages:'3–5',minutes:30,format:'Lesson plan',price:59,supply:'Household',setup:5,description:'Start a tiny garden and observe what plants need to grow. A playful introduction to asking questions and recording changes.',materials:['Seeds','Paper towels','Clear cups','Water'],lessons:['Meet a seed','Set up your garden','Observe and draw'],color:'#e2f3dd'},
 {id:'paper-circuits',title:'Light up a paper city',subject:'electronics',ages:'6–10',minutes:60,format:'Complete course',price:99,supply:'Specialty kit',setup:10,description:'Discover closed circuits while designing a city of glowing paper buildings. Adult handling of batteries is required.',materials:['Cardstock','Copper tape','LEDs','Enclosed AA battery holder'],lessons:['What is a circuit?','Meet the components','Build a safe circuit','Find the break','Make a switch','Sketch a city','Fold buildings','Add lights','Test the city','Share and reflect'],color:'#fff0ba'},
 {id:'robot-rescue',title:'Mission: robot rescue',subject:'robotics',ages:'11–14',minutes:60,format:'Complete course',price:99,supply:'Specialty kit',setup:10,description:'Plan a rescue route, program a robot, and learn why testing is part of every great invention. A compatible robot kit is required separately.',materials:['Programmable robot kit','Computer or tablet','Tape','Cardboard obstacles'],lessons:['The rescue mission','Meet your robot','Plan a route','Sequence commands','Test movement','Use loops','Explore sensors','Debug your route','Run the mission','Reflect and improve'],color:'#fbe3d8'},
 {id:'code-without-screens',title:'Coding without a screen',subject:'coding',ages:'6–10',minutes:30,format:'Workbook',price:69,supply:'Household',setup:3,description:'Become a human robot, write a sequence, and debug a maze with printable, unplugged coding challenges.',materials:['Paper','Pencils','Grid cards'],lessons:['Give clear instructions','Build a sequence','Debug a maze','Repeat with loops'],color:'#eee3fa'},
 {id:'kitchen-discoveries',title:'Kitchen science discoveries',subject:'biology',ages:'6–10',minutes:45,format:'Video lessons',price:89,supply:'Household',setup:5,description:'Investigate everyday changes through observation and simple experiments with an adult facilitator.',materials:['Clear cups','Water','Salt','Spoons','Paper towels'],lessons:['Ask a testable question','Compare materials','Observe a change','Record your findings','Explain your discovery'],color:'#e2f3dd'},
 {id:'bridge-builders',title:'The great bridge challenge',subject:'physics',ages:'11–14',minutes:60,format:'Lesson plan',price:59,supply:'Low cost',setup:5,description:'Design a paper bridge, test its strength, and use evidence to make your next version even better.',materials:['Paper','Tape','Books','Small test weights'],lessons:['Explore structures','Design your bridge','Test and redesign'],color:'#e3eafd'},
 {id:'supply-planner',title:'Maker materials checklist',subject:'electronics',ages:'6–10',minutes:30,format:'Materials list',price:50,supply:'Low cost',setup:2,description:'A printable checklist for setting up a small maker station, with facilitator preparation notes.',materials:['Printer','Pencil'],lessons:['Plan your maker station'],color:'#fff0ba'},
 {id:'chem-lab-secrets',title:'Chem-Lab Secrets camp week',subject:'biology',ages:'6–10',minutes:60,format:'Complete course',price:99,supply:'Household',setup:10,track:'week-camp',description:'A five-day kitchen-chemistry camp track: fizzing reactions, polymers, color changes, and a Friday showcase lab for families.',materials:['Baking soda','White vinegar','Food coloring','Clear cups','Measuring spoons','Safety goggles','White school glue','Cornstarch','Red cabbage (for a color indicator)','Zip-top bags'],lessons:['Monday: what is a scientist?','Monday: safe lab habits','Tuesday: fizz and bubbles','Tuesday: measure the reaction','Wednesday: slime and polymers','Wednesday: oobleck investigation','Thursday: cabbage color detectives','Thursday: plan a showcase test','Friday: rehearse the demonstration','Friday: family showcase lab'],color:'#e2f3dd'},
 {id:'senses-explorers',title:'Five senses explorers',subject:'biology',ages:'3–5',minutes:30,format:'Video lessons',price:89,supply:'Household',setup:5,description:'Look, listen, touch, and smell. Short sensory stations help little learners describe their world with new words.',materials:['Small containers with lids','Cotton balls','Herbs or spices (allergy-checked)','Textured fabric scraps','Bell or shaker','Hand lens'],lessons:['Look closely','Listen and match','Touch and describe','Smell detectives','Sense sorting game'],color:'#e2f3dd'},
 {id:'backyard-scientist',title:'The backyard scientist',subject:'biology',ages:'6–10',minutes:30,format:'PDF Book',price:79,supply:'Household',setup:3,description:'A printable PDF field guide with bug hunts, leaf rubbings, and weather journals to carry outdoors.',materials:['Printed PDF pages or a tablet','Clipboard','Pencil and crayons','Hand lens'],lessons:['Chapter 1: Be a nature observer','Chapter 2: Leaf and bark rubbings','Chapter 3: Minibeast hunt','Chapter 4: Weather watch journal','Chapter 5: Share your field notes'],color:'#e2f3dd'},
 {id:'kitchen-chemistry-supplies',title:'Kitchen chemistry supply list',subject:'biology',ages:'6–10',minutes:30,format:'Materials list',price:50,supply:'Household',setup:2,description:'A grocery-store shopping list for a full season of fizzing, mixing, and color-change activities, with storage tips.',materials:['Baking soda','White vinegar','Cornstarch','Food coloring','Dish soap','Clear plastic cups','Measuring spoons','Zip-top bags'],lessons:['Plan your kitchen chemistry shelf'],color:'#e2f3dd'},
 {id:'straw-rocket-lab',title:'Straw rocket launch lab',subject:'physics',ages:'6–10',minutes:45,format:'Video lessons',price:89,supply:'Low cost',setup:3,description:'Build paper rockets, launch them with a breath, and measure how fins and nose cones change the flight.',materials:['Drinking straws','Paper','Tape','Scissors (adult-supervised)','Measuring tape','Safety glasses'],lessons:['Meet the rocket','Build the body','Add fins and a nose cone','Launch and measure','Change one thing'],color:'#e3eafd'},
 {id:'simple-machines-book',title:'Simple machines storybook',subject:'physics',ages:'6–10',minutes:30,format:'PDF Book',price:79,supply:'Household',setup:3,description:'Follow a curious inventor through levers, ramps, wheels, and pulleys, with try-it-now pages after every chapter.',materials:['Printed PDF pages or a tablet','Ruler','Small toy car','Books for a ramp','String'],lessons:['Chapter 1: The mighty lever','Chapter 2: Ramps make it easier','Chapter 3: Wheels and axles','Chapter 4: Pulleys lift loads','Chapter 5: Invent a machine'],color:'#e3eafd'},
 {id:'engineer-notebook',title:'Engineer’s design notebook',subject:'physics',ages:'11–14',minutes:45,format:'Workbook',price:69,supply:'Low cost',setup:2,description:'Printable design-challenge pages: define the problem, sketch ideas, test, and record improvements for any build.',materials:['Printed workbook','Pencil','Ruler','Graph paper'],lessons:['Define the problem','Brainstorm and sketch','Choose and build','Test and record data','Improve and present'],color:'#e3eafd'},
 {id:'squishy-circuits',title:'Squishy circuits with conductive dough',subject:'electronics',ages:'6–10',minutes:45,format:'Lesson plan',price:59,supply:'Low cost',setup:10,description:'Mix salty play dough that conducts electricity, light an LED, and discover what makes a circuit complete.',materials:['Flour','Salt','Water','Vegetable oil','Sugar (for insulating dough)','LEDs','Enclosed AA battery holder with batteries'],lessons:['Make conductive dough','Light your first LED','Insulators vs conductors'],color:'#fff0ba'},
 {id:'circuit-detectives',title:'Circuit detectives video series',subject:'electronics',ages:'11–14',minutes:60,format:'Video lessons',price:89,supply:'Specialty kit',setup:10,description:'Breadboards, switches, and simple logic: short videos guide older learners through building and troubleshooting real circuits.',materials:['Solderless breadboard','Jumper wires','LEDs','220 ohm resistors','Push buttons','Enclosed AA battery pack'],lessons:['Meet the breadboard','Series and parallel','Add a switch','AND and OR with buttons','Troubleshoot like a detective'],color:'#fff0ba'},
 {id:'make-it-glow',title:'Make it glow',subject:'electronics',ages:'6–10',minutes:30,format:'PDF Book',price:79,supply:'Specialty kit',setup:5,description:'A PDF book of light-up crafts—greeting cards, nightlights, and badges—built with copper tape, coin cells, and LEDs.',materials:['Copper tape','LEDs','Coin cell batteries (adult-handled)','Cardstock','Binder clips'],lessons:['Chapter 1: What makes light?','Chapter 2: A light-up card','Chapter 3: Add a paper switch','Chapter 4: Glow badge','Chapter 5: Design your own'],color:'#fff0ba'},
 {id:'build-a-bot-week',title:'Build-a-Bot Week',subject:'robotics',ages:'6–10',minutes:60,format:'Complete course',price:99,supply:'Low cost',setup:10,track:'week-camp',description:'A five-day camp track: design cardboard robots, add moving joints, program “human robots,” and present at a Friday robot showcase.',materials:['Cardboard boxes','Paper cups','Brass fasteners','Tape','Markers','Rubber bands','Craft sticks'],lessons:['Monday: what is a robot?','Monday: sketch your bot','Tuesday: build the body','Tuesday: joints that move','Wednesday: human-robot commands','Wednesday: program a route','Thursday: sensors in nature and machines','Thursday: improve your design','Friday: rehearse the showcase','Friday: robot showcase'],color:'#fbe3d8'},
 {id:'hydraulic-arm',title:'Hydraulic robot arm',subject:'robotics',ages:'11–14',minutes:60,format:'Lesson plan',price:59,supply:'Low cost',setup:10,description:'Use water-filled syringes and tubing to build a cardboard arm that lifts and grabs—real hydraulics, everyday materials.',materials:['Plastic syringes (no needles)','Clear tubing','Cardboard','Craft sticks','Brass fasteners','Tape','Water and towels'],lessons:['How hydraulics work','Build the arm','Lift and grab challenge'],color:'#fbe3d8'},
 {id:'robot-kit-checklist',title:'Robot kit setup checklist',subject:'robotics',ages:'11–14',minutes:30,format:'Materials list',price:50,supply:'Specialty kit',setup:5,description:'A setup checklist for third-party robot kits, such as the OpenDuck robot kit from Tinkr: charging, devices, storage, and team roles. Kits are sold separately.',materials:['Compatible robot kit (sold separately)','Charging cables','Computer or tablet','Labeled storage bins','Masking tape for test courses'],lessons:['Prepare your robot station'],color:'#fbe3d8'},
 {id:'robot-logbook',title:'Robot mission logbook',subject:'robotics',ages:'6–10',minutes:30,format:'Workbook',price:69,supply:'Low cost',setup:2,description:'Printable mission pages for planning routes, writing command sequences, and recording what each robot test revealed.',materials:['Printed workbook','Pencil','Grid paper','Toy or floor robot (optional)'],lessons:['Plan a mission','Write the commands','Test and record','Debug and retry'],color:'#fbe3d8'},
 {id:'algorithm-adventures',title:'Algorithm adventures',subject:'coding',ages:'6–10',minutes:45,format:'Complete course',price:99,supply:'Household',setup:5,description:'Ten lessons move from unplugged algorithms to block-based coding in free browser tools like Scratch, ending with a playable game.',materials:['Computer or tablet with a web browser','Printable grid cards','Dice','Pencils','Free Scratch or MakeCode account (adult-managed)'],lessons:['What is an algorithm?','Sequences with arrows','Loops in dance moves','Debug a broken path','Meet block coding','Events and sprites','Loops on screen','Conditionals: if this, then that','Design a mini game','Share and play-test'],color:'#eee3fa'},
 {id:'pattern-detectives',title:'Pattern detectives',subject:'coding',ages:'3–5',minutes:30,format:'Lesson plan',price:59,supply:'Household',setup:3,description:'Sort, stack, and repeat: hands-on pattern games build early math thinking with blocks, buttons, and colored paper.',materials:['Building blocks','Buttons or counters','Colored paper strips','Sorting trays'],lessons:['Find a pattern','Make a pattern','Fix the pattern'],color:'#eee3fa'},
 {id:'shape-builders',title:'3D shape builders',subject:'coding',ages:'6–10',minutes:30,format:'PDF Book',price:79,supply:'Household',setup:3,description:'A PDF book of build-and-measure challenges: make cubes and pyramids from straws, count faces and edges, and compare sizes.',materials:['Printed PDF pages or a tablet','Drinking straws','Pipe cleaners or clay','Ruler or measuring tape','Dice'],lessons:['Chapter 1: Flat vs solid','Chapter 2: Build a cube','Chapter 3: Pyramids and prisms','Chapter 4: Measure and compare','Chapter 5: Design a shape city'],color:'#eee3fa'},
 {id:'block-coding-games',title:'Make a game with block coding',subject:'coding',ages:'11–14',minutes:60,format:'Video lessons',price:89,supply:'Household',setup:5,description:'Video walkthroughs guide older learners through designing, coding, and debugging a playable game in a free block-based editor.',materials:['Computer or tablet with a web browser','Free Scratch account (adult-managed)','Headphones (optional)'],lessons:['Plan your game','Sprites and backdrops','Movement with events','Score with variables','Debug and polish'],color:'#eee3fa'},
];
export const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(cents/100);
export const findProduct=(id:string)=>products.find(p=>p.id===id);
export const heroImage='https://d2pn8kiwq2w21t.cloudfront.net/images/paperhelicopter_materials.width-1320.jpg';
export const sampleVideo='https://www.youtube-nocookie.com/embed/HrKRWsrZuYc';
export const sampleSource='https://www.jpl.nasa.gov/edu/resources/project/make-a-paper-mars-helicopter-2/';
export const amazonSearch=(item:string)=>'https://www.amazon.com/s?k='+encodeURIComponent(item.replace(/\(.*?\)/g,'').trim());
