import {InputError,textField,validKey} from './core.mjs';

export const SUBJECTS=['biology','physics','electronics','robotics','coding'];
export const FORMATS=['Complete course','Video lessons','Workbook','Lesson plan','Materials list'];
const pick=(v,values,label)=>{if(!values.includes(v))throw new InputError('Choose a valid '+label+'.');return v;};
const str=(v,label,max=200,optional=false)=>textField(v,label,max,!optional);
export const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof value==='string'?new TextEncoder().encode(value):value))).map(x=>x.toString(16).padStart(2,'0')).join('');
export function validateContent(value){
 if(!value||typeof value!=='object')throw new InputError('Enter curriculum details.');
 const d={title:str(value.title,'Title',120),subject:pick(value.subject,SUBJECTS,'subject'),ages:pick(value.ages,['3–5','6–10','11–14'],'age group'),format:pick(value.format,FORMATS,'format'),minutes:value.minutes,price:value.price,supply:pick(value.supply,['Household','Low cost','Specialty kit'],'supply level'),description:str(value.description,'Description',3000),outcomes:str(value.outcomes,'Learning outcomes',4000),standards:str(value.standards??'','Standards mapping',4000,true),safety:str(value.safety,'Safety notes',4000),track:pick(value.track??'single',['single','week-camp'],'track'),sample:value.sample===true,materials:value.materials,steps:value.steps};
 if(!Number.isInteger(d.minutes)||d.minutes<5||d.minutes>180)throw new InputError('Activity time must be 5–180 whole minutes.');
 if(!Number.isInteger(d.price)||d.price<100||d.price>100000)throw new InputError('Price must be 100–100,000 cents.');
 if(!Array.isArray(d.materials)||!d.materials.length||d.materials.length>100)throw new InputError('Add 1–100 materials.');d.materials=d.materials.map(x=>str(x,'Material',200));
 if(!Array.isArray(d.steps)||!d.steps.length||d.steps.length>40)throw new InputError('Add 1–40 lessons.');
 d.steps=d.steps.map((s,i)=>({id:s?.id??crypto.randomUUID(),title:str(s?.title,'Lesson '+(i+1)+' title',150),instructions:str(s?.instructions,'Lesson instructions',6000),prep:str(s?.prep,'Preparation notes',3000),minutes:s?.minutes}));
 if(d.steps.some(s=>typeof s.id!=='string'||!/^[-a-zA-Z0-9_]{1,80}$/.test(s.id))||new Set(d.steps.map(s=>s.id)).size!==d.steps.length)throw new InputError('Lesson identifiers must be unique and valid.');
 if(d.steps.some(s=>!Number.isInteger(s.minutes)||s.minutes<1||s.minutes>120))throw new InputError('Each video lesson duration must be 1–120 minutes.');
 return d;
}
export function publicProduct(row){const d=JSON.parse(row.published);return {id:row.id,title:d.title,subject:d.subject,ages:d.ages,format:d.format,minutes:d.minutes,price:d.price,supply:d.supply,description:d.description,outcomes:d.outcomes,standards:d.standards,safety:d.safety,track:d.track,sample:d.sample,materials:d.materials,lessons:d.steps.map(s=>s.title),color:{biology:'#e2f3dd',physics:'#e3eafd',electronics:'#fff0ba',robotics:'#fbe3d8',coding:'#eee3fa'}[d.subject],custom:true,status:row.status,revision:row.published_revision};}
export function contentService({db,settings={},now=()=>Date.now()}){
 const q=(sql,...args)=>db.prepare(sql).bind(...args);
 const audit=(u,action,target,detail='')=>q('INSERT INTO audit_log(id,user_id,action,target,detail,created_at) VALUES(?,?,?,?,?,?)',crypto.randomUUID(),u.userId,action,target,detail,now());
 async function role(u){
  const ids=(settings.CONTENT_ADMIN_USER_IDS??'').split(',').map(s=>s.trim()).filter(Boolean),emails=(settings.CONTENT_ADMIN_EMAILS??'').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);
  // Bootstrap only a platform-verified allowlisted owner, then persist the stable Sites user ID.
  if(ids.includes(u.userId)||emails.includes(String(u.email??'').toLowerCase()))await q("INSERT INTO content_users(user_id,name,email,role,created_at) VALUES(?,?,?,'admin',?) ON CONFLICT(user_id) DO UPDATE SET role='admin'",u.userId,u.displayName??'',u.email??'',now()).run();
  return (await q('SELECT role FROM content_users WHERE user_id=?',u.userId).first())?.role??'reader';
 }
 async function admin(u){if(await role(u)!=='admin')throw new InputError('Only a curriculum administrator can do this.',403);}
 async function editor(u){if(!['creator','admin'].includes(await role(u)))throw new InputError('Request creator access before adding curriculum.',403);}
 async function owned(u,id){await editor(u);const row=await q('SELECT * FROM content_courses WHERE id=?',String(id??'')).first();if(!row)throw new InputError('Curriculum not found.',404);if(row.owner_id!==u.userId&&await role(u)!=='admin')throw new InputError('This curriculum belongs to another creator.',403);return row;}
 async function request(u){const r=await role(u);if(r==='reader')await q("INSERT INTO content_users(user_id,name,email,role,created_at) VALUES(?,?,?,'pending',?) ON CONFLICT(user_id) DO NOTHING",u.userId,u.displayName??'',u.email??'',now()).run();return {role:await role(u)};}
 async function grant(u,id,next){await admin(u);pick(next,['creator','reader'],'creator access');if(id===u.userId)throw new InputError('You cannot change your own administrator access.');const target=await q('SELECT role FROM content_users WHERE user_id=?',String(id??'')).first();if(!target||target.role==='admin')throw new InputError('Choose a pending creator or existing creator.');await db.batch([q('UPDATE content_users SET role=? WHERE user_id=?',next,id),audit(u,'creator-role',id,next)]);return {saved:true};}
 async function create(u,key){await editor(u);validKey(key);const id='course-'+(await digest(u.userId+':'+key)).slice(0,24);const count=await q('SELECT count(*) AS n FROM content_courses WHERE owner_id=?',u.userId).first();if(count.n>=200&&!await q('SELECT id FROM content_courses WHERE id=?',id).first())throw new InputError('Creator course limit reached.',429);await q("INSERT INTO content_courses(id,owner_id,draft,status,revision,created_at,updated_at) VALUES(?,?,'{}','draft',0,?,?) ON CONFLICT(id) DO NOTHING",id,u.userId,now(),now()).run();return detail(u,id);}
 async function detail(u,id){const row=await owned(u,id);const assets=await q("SELECT id,course_id,kind,lesson_index,language,name,mime,size,status,provider_id,created_at FROM content_assets WHERE course_id=? AND status!='deleted' ORDER BY created_at",id).all();return {...row,draft:JSON.parse(row.draft),published:row.published?JSON.parse(row.published):null,assets:assets.results};}
 async function list(u){const r=await role(u);return {role:r,courses:['creator','admin'].includes(r)?(await q('SELECT id,owner_id,draft,status,revision,published_revision,updated_at FROM content_courses WHERE owner_id=? OR ?=1 ORDER BY updated_at DESC LIMIT 250',u.userId,r==='admin'?1:0).all()).results.map(row=>({...row,draft:JSON.parse(row.draft)})):[],users:r==='admin'?(await q('SELECT user_id,name,email,role,created_at FROM content_users ORDER BY created_at DESC LIMIT 250').all()).results:[],logs:r==='admin'?(await q('SELECT action,target,detail,created_at FROM audit_log ORDER BY created_at DESC LIMIT 100').all()).results:[],mediaReady:!!(settings.MUX_TOKEN_ID&&settings.MUX_TOKEN_SECRET),emailReady:!!(settings.RESEND_API_KEY&&settings.EMAIL_FROM)};}
 async function save(u,id,revision,data){const row=await owned(u,id);if(!Number.isInteger(revision)||row.revision!==revision)throw new InputError('A newer version exists. Reload before saving.',409);const next=validateContent(data),old=JSON.parse(row.draft);if(row.published||await q('SELECT id FROM content_assets WHERE course_id=? LIMIT 1',id).first()){if((old.steps??[]).some((s,i)=>next.steps[i]?.id!==s.id))throw new InputError('Existing lesson order must be preserved once files are attached or a course is published. Add new lessons at the end.');}const draft=JSON.stringify(next);const result=await q("UPDATE content_courses SET draft=?,revision=revision+1,updated_at=?,status=CASE WHEN status='review' THEN 'draft' ELSE status END WHERE id=? AND revision=?",draft,now(),id,revision).run();if(!result.meta.changes)throw new InputError('Another editor saved first. Reload to avoid overwriting changes.',409);await audit(u,'course-save',id,String(revision+1)).run();return detail(u,id);}
 async function transition(u,id,revision,action){const row=await owned(u,id);if(row.revision!==revision)throw new InputError('Reload this curriculum before changing its status.',409);pick(action,['review','publish','archive'],'action');if(action!=='review')await admin(u);if(row.status==='archive'&&action==='review')throw new InputError('Archived curriculum remains hidden until an administrator republishes it.',409);if(action==='publish'||action==='review'){
  const d=validateContent(JSON.parse(row.draft));
  if(!d.sample){const assets=(await q("SELECT kind,lesson_index,language,status FROM content_assets WHERE course_id=? AND status='ready'",id).all()).results;
   for(const kind of ['plan','worksheet'])if(!assets.some(a=>a.kind===kind&&a.language==='en'))throw new InputError('Upload an English '+kind+' PDF before publishing premium content.');
   if(['Complete course','Video lessons'].includes(d.format))for(let i=0;i<d.steps.length;i++)if(!assets.some(a=>a.kind==='video'&&a.lesson_index===i))throw new InputError('Every video lesson needs a processed student video.');
   if(d.format==='Complete course'&&(d.steps.length!==10||d.steps.some(s=>s.minutes!==30)))throw new InputError('Complete courses require ten 30-minute lessons as specified in the curriculum brief.');
  }
 }
 const ready=(await q("SELECT id,kind,lesson_index,language FROM content_assets WHERE course_id=? AND status='ready' ORDER BY created_at,id",id).all()).results;const assets=Array.from(new Map(ready.map(a=>[a.kind+':'+a.lesson_index+':'+a.language,a.id])).values());
 const result=action==='publish'?await q("UPDATE content_courses SET status='published',published=draft,published_assets=?,published_revision=revision,revision=revision+1,updated_at=? WHERE id=? AND revision=?",JSON.stringify(assets),now(),id,revision).run():await q('UPDATE content_courses SET status=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?',action,now(),id,revision).run();
 if(!result.meta.changes)throw new InputError('The curriculum changed. Reload and try again.',409);await audit(u,'course-'+action,id).run();return detail(u,id);
 }
 async function catalog(includeArchived=false){const rows=(await q("SELECT id,published,published_assets,status,published_revision FROM content_courses WHERE published IS NOT NULL AND (status!='archive' OR ?=1)",includeArchived?1:0).all()).results;const images=(await q("SELECT id,course_id FROM content_assets WHERE kind='image' AND status='ready'").all()).results;return rows.map(row=>({...publicProduct(row),coverAsset:images.find(a=>a.course_id===row.id&&JSON.parse(row.published_assets??'[]').includes(a.id))?.id}));}
 async function asset(u,id){const a=await q('SELECT * FROM content_assets WHERE id=?',String(id??'')).first();if(!a||a.status==='deleted')throw new InputError('File not found.',404);await owned(u,a.course_id);return a;}
 async function assetMeta(u,b){await owned(u,b.courseId);pick(b.kind,['plan','worksheet','supplies','image','captions','video','prep','preview'],'file purpose');pick(b.language,['en','es'],'language');const row=await owned(u,b.courseId),d=JSON.parse(row.draft);if(!Number.isInteger(b.lesson)||b.lesson<0||b.lesson>=(d.steps?.length??0))throw new InputError('Save your lesson list before uploading files.');return {id:crypto.randomUUID(),courseId:row.id,revision:row.revision,lessonId:d.steps[b.lesson].id,ownerId:u.userId,kind:b.kind,language:b.language,lesson:b.lesson,name:str(b.name,'File name',180).replace(/[\\/<>:"|?*\x00-\x1f]/g,'_')};}
 async function attachAsset(u,m,a){
  await owned(u,m.courseId);
  const result=await db.batch([
   q("INSERT INTO content_assets(id,course_id,owner_id,kind,lesson_index,language,name,mime,size,storage_key,provider_id,status,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM content_courses WHERE id=? AND revision=? AND json_extract(draft,?)=? ON CONFLICT(id) DO UPDATE SET status=excluded.status,created_at=excluded.created_at",a.id,m.courseId,u.userId,m.kind,m.lesson,m.language,m.name,a.mime,a.size,a.key??null,a.providerId??null,a.status,now(),m.courseId,m.revision,'$.steps['+m.lesson+'].id',m.lessonId),
   q('UPDATE content_courses SET revision=revision+1,updated_at=? WHERE id=? AND revision=? AND changes()>0',now(),m.courseId,m.revision)
  ]);
  if(!result[0].meta.changes)throw new InputError('The lesson changed during upload. Reopen the lesson and upload the file again.',409);
  return {id:a.id,status:a.status};
 }
 async function remove(u,id){const a=await asset(u,id);const results=await db.batch([q("UPDATE content_assets SET status='deleted' WHERE id=? AND NOT EXISTS(SELECT 1 FROM content_courses c,json_each(coalesce(c.published_assets,'[]')) j WHERE c.id=? AND j.value=?)",id,a.course_id,id),q('UPDATE content_courses SET revision=revision+1,updated_at=? WHERE id=? AND changes()>0',now(),a.course_id)]);if(!results[0].meta.changes)throw new InputError('This file is part of a published revision. Upload its replacement and publish a new revision first.',409);await audit(u,'asset-delete',id).run();return {removed:true};}
 return {role,admin,editor,owned,request,grant,create,detail,list,save,transition,catalog,asset,assetMeta,attachAsset,remove,audit};
}
