export class InputError extends Error { constructor(message,status=400){super(message);this.status=status;} }
export function cleanIds(value,valid){if(!Array.isArray(value)||value.length>30||value.some(x=>typeof x!=='string'||!valid.includes(x)))throw new InputError('Some cart items are invalid. Refresh the catalog and try again.');return [...new Set(value)];}
export function textField(value,name,max=160,required=true){if(typeof value!=='string'||value.length>max)throw new InputError(`${name} must be ${max} characters or fewer.`);const cleaned=value.trim();if(required&&!cleaned)throw new InputError(`${name} is required.`);return cleaned;}
export function validateLead(body){
 const name=textField(body.name,'Name',100),email=textField(body.email,'Email',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new InputError('Enter a valid email address.');
 if(!['pilot','quote','po'].includes(body.kind))throw new InputError('Choose a valid request type.');if(!['parent','tutor','daycare','afterschool','camp','other'].includes(body.role))throw new InputError('Choose your role.');
 const sites=Number(body.sites??1);if(!Number.isInteger(sites)||sites<1||sites>1000)throw new InputError('Number of sites must be between 1 and 1,000.');if(body.consent!==true)throw new InputError('Please confirm that you are an adult and agree to save this request.');
 return {name,email,role:body.role,kind:body.kind,sites,organization:textField(body.organization??'','Organization',160,false),notes:textField(body.notes??'','Notes',2000,false),po:textField(body.po??'','PO number',80,false)};
}
export function validKey(value){if(typeof value!=='string'||!/^[-a-zA-Z0-9_]{16,80}$/.test(value))throw new InputError('Invalid request key. Reload and try again.');return value;}
export function assertSameOrigin(request){const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)throw new InputError('This request must come from this website.',403);}
export function assertTestKey(key){if(!key||!key.startsWith('sk_test_'))throw new InputError('Stripe test checkout is not configured. No charge was made.',503);}
export function isPayableSession(session,order){return session.mode==='payment'&&session.payment_status==='paid'&&session.status==='complete'&&session.livemode===false&&session.currency==='usd'&&session.amount_total===order.total&&session.client_reference_id===order.id&&session.metadata?.user_id===order.user_id;}
export async function verifySignature(payload,header,secret,now=Date.now()){
 if(!secret||!header)return false;const parts=header.split(','),ts=parts.find(x=>x.startsWith('t='))?.slice(2),signatures=parts.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));if(!ts||!/^\d+$/.test(ts)||Math.abs(now/1000-Number(ts))>300)return false;
 const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${ts}.${payload}`)))).map(b=>b.toString(16).padStart(2,'0')).join('');return signatures.some(x=>{if(x.length!==sig.length)return false;let diff=0;for(let i=0;i<sig.length;i++)diff|=x.charCodeAt(i)^sig.charCodeAt(i);return diff===0;});
}
export function filterCatalog(items,{search='',subject='all',age='all',format='all',duration='all',supply='all'}={}){const q=search.trim().toLowerCase().slice(0,200);return items.filter(p=>(subject==='all'||p.subject===subject)&&(age==='all'||p.ages===age)&&(format==='all'||p.format===format)&&(duration==='all'||p.minutes<=Number(duration))&&(supply==='all'||p.supply===supply)&&[p.title,p.description,...p.materials].join(' ').toLowerCase().includes(q));}
