import {subjects,type Product} from './catalog';
import {streamGuides} from './streams';
import {hasLessonVideos} from './placeholder-videos.mjs';
// Placeholder teaching documents for the sample catalog: lesson plan, student workbook and bill of materials, alone or combined.
export type CourseDocument='bundle'|'plan'|'worksheet';
type Section={title:string;lines:string[]};
const timing=(minutes:number)=>{const rest=Math.max(minutes-10,10),explore=Math.ceil(rest/2);return {explore,test:rest-explore};};
const safetyLines:Record<string,string[]>={
 en:['An adult reviews every activity before use and supervises learners at all times.','Check allergies before using foods, spices, latex or plant materials.','Adults handle sharp tools, hot items, batteries and electrical connections.','Keep small parts away from children under three.'],
 es:['Un adulto revisa cada actividad antes de usarla y supervisa a los participantes en todo momento.','Verifique alergias antes de usar alimentos, especias, látex o plantas.','Los adultos manejan herramientas filosas, objetos calientes, pilas y conexiones eléctricas.','Mantenga las piezas pequeñas lejos de niños menores de tres años.'],
};
const streamSafety:Record<string,string>={biology:'Wear goggles for fizzing reactions and never taste experiments.',electronics:'Coin and button batteries are a swallowing hazard. Keep them locked away and count them back in.',robotics:'Keep cords tidy and charge devices only under adult supervision.',physics:'Launch and test only in a clear area, away from faces.',coding:'Adults manage any online accounts. Learners never share personal information online.'};
export function courseSections(p:Product,kind:CourseDocument,lang:'en'|'es'):Section[]{
 const stream=subjects.find(s=>s.id===p.subject),guide=streamGuides[p.subject],{explore,test}=timing(p.minutes),videos=hasLessonVideos(p),setup=p.setup??5;
 if(lang==='es'){
  const cover={title:p.title,lines:['Plan de lección y cuaderno del estudiante (traducción preliminar)',`Edades sugeridas: ${p.ages} | Sesiones de ${p.minutes} minutos | Preparación: unos ${setup} minutos`,'Los títulos de las lecciones aparecen en inglés. Un adulto revisa cada actividad antes de usarla.']};
  const plan=p.lessons.map((title,i)=>({title:`Lección ${i+1}: ${title}`,lines:[`Tiempo: ${p.minutes} minutos | Edades ${p.ages}`,...(videos?[`Video: lección ${i+1} en su aula de SwIRL.`]:[]),'1. Introducción (5 min): Muestre el video o una demostración breve. Pregunte: "¿Qué crees que va a pasar?"',`2. Explorar (${explore} min): Los equipos trabajan en la actividad. Pregunte: "¿Qué observaste?"`,`3. Probar y mejorar (${test} min): Cambien una sola cosa, vuelvan a probar y anoten el resultado.`,'4. Compartir (5 min): Cada equipo comparte un descubrimiento y una pregunta.']}));
  const workbook=p.lessons.map((title,i)=>({title:`Página del estudiante ${i+1}: ${title}`,lines:['Nombre: ______________________________','Mi pregunta: __________________________________________','Mi predicción: ________________________________________','Lo que probé: _________________________________________','Lo que observé: _______________________________________','Dibújalo aquí:','','','','La próxima vez yo: ____________________________________']}));
  const materials={title:'Lista de materiales',lines:[...p.materials.map(m=>'- '+m),'Cantidad: ajuste según el tamaño del grupo. Los materiales y kits se compran por separado.']},safety={title:'Guía de seguridad',lines:safetyLines.es};
  return kind==='plan'?[cover,...plan,materials,safety]:kind==='worksheet'?[cover,...workbook]:[cover,...plan,...workbook,materials,safety];
 }
 const cover={title:p.title,lines:[`${stream?.name??p.subject} | ${p.format}`,`Suggested ages ${p.ages} | ${p.minutes}-minute sessions | About ${setup} minutes of setup`,'An adult reviews every activity before use and adapts it to the learners’ ages and needs.',kind==='bundle'?'Inside: facilitator lesson plan, student workbook, bill of materials, safety guide and standards alignment.':kind==='plan'?'Inside: facilitator lesson plan, bill of materials, safety guide and standards alignment.':'Inside: one student workbook page per lesson.',videos?`Videos: ${p.lessons.length} lesson videos stream from your SwIRL classroom.`:'This resource is a printable '+p.format.toLowerCase()+'.']};
 const overview={title:'Facilitator lesson plan',lines:[...(guide?['Stream focus: '+guide.focus,'Key deliverables: '+guide.deliverables.join(', ')+'.','Learning outcomes:',...guide.outcomes.map(o=>'- '+o)]:[]),'60-second prep: gather '+p.materials.join(', ')+'.',...(guide?[...guide.mistakes.map(m=>'Watch for: '+m),...guide.cleanup.map(c=>'Cleanup hack: '+c)]:[])]};
 const plan=p.lessons.map((title,i)=>({title:`Lesson ${i+1}: ${title}`,lines:[`Time: ${p.minutes} minutes | Ages ${p.ages}`,...(videos?[`Video: lesson ${i+1} plays in your SwIRL classroom.`]:[]),'1. Hook (5 min): Show the video or a quick demonstration. Ask: "What do you think will happen?"',`2. Explore (${explore} min): Teams work on "${title}". Circulate and ask: "What did you notice?"`,`3. Test and improve (${test} min): Change one thing, try again and record the result on the student page.`,'4. Share (5 min): Each team shares one discovery and one new question.','Check for understanding: can learners explain what changed and why?']}));
 const workbook=p.lessons.map((title,i)=>({title:`Student page ${i+1}: ${title}`,lines:['Name: ______________________________','My question: _________________________________________','My prediction: _______________________________________','What I tried: ________________________________________','What I noticed: ______________________________________','Draw it here:','','','','Next time I would: ___________________________________']}));
 const materials={title:'Bill of materials',lines:[...p.materials.map(m=>'- '+m+' (quantity: adjust for group size)'),'Source items from a grocery store or online retailers such as Amazon. Supplies and kits are not included.']};
 const safety={title:'Safety guide',lines:[...(p.safety?[p.safety]:[]),...safetyLines.en,...(streamSafety[p.subject]?[streamSafety[p.subject]]:[])]};
 const standards={title:'Standards alignment',lines:[...(p.standards?[p.standards]:guide?.standards.map(s=>s.code+': '+s.text)??[]),'Confirm standards alignment against your state or program requirements.']};
 return kind==='plan'?[cover,overview,...plan,materials,safety,standards]:kind==='worksheet'?[cover,...workbook]:[cover,overview,...plan,...workbook,materials,safety,standards];
}
