import {linkYoutube} from './youtube.mjs';
import {storedVideo,videoStream,validateIntroduction} from './video-server';
import {sampleSource} from './catalog';
import {db,settings,user,json,body,stripe} from './server';
import {content,bucket,catalog,coursePermission,courseAssets} from './content-server';
import {InputError,assertSameOrigin,validateLead,textField} from './core.mjs';
import {digest} from './content.mjs';
import {boundedBytes,validateFile,documentPdf,bundlePdf,csvCell,sanitizeCsv} from './files.mjs';
import {startVideo,syncVideo,playback,removeVideo} from './media';
import {programBilling} from './program-billing.mjs';
import {emailService} from './email.mjs';
export const mail=()=>emailService({db:db(),settings:settings()});
export const program=()=>programBilling({db:db(),settings:settings(),stripe,content:content(),catalog,email:mail()});
const fileResponse=(bytes:any,mime:string,name:string,inline=false)=>new Response(bytes,{headers:{'Content-Type':mime,'Content-Disposition':`${inline?'inline':'attachment'}; filename="${name.replace(/[^a-zA-Z0-9_.-]/g,'_')}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'; style-src 'unsafe-inline'",'Referrer-Policy':'no-referrer'}});
export async function featureGet(req:Request):Promise<Response|null>{const url=new URL(req.url),action=url.pathname.slice(5);
 if(action==='video-stream')return videoStream(req);
 if(action==='catalog')return json({products:await catalog(),site:{...JSON.parse((await db().prepare("SELECT data FROM site_content WHERE id='public'").first<any>())?.data??'{}'),logos:(await db().prepare("SELECT id,name FROM content_assets WHERE kind='partner-logo' AND status='ready' ORDER BY created_at").all()).results}});
 if(action==='public-logo'){const a=await db().prepare("SELECT * FROM content_assets WHERE id=? AND kind='partner-logo' AND status='ready'").bind(url.searchParams.get('id')).first<any>();if(!a)throw new InputError('Logo not found.',404);const file=await bucket().get(a.storage_key);if(!file)throw new InputError('Logo unavailable.',404);return fileResponse(file.body,a.mime,a.id,true);}
 if(action==='public-image'){const a=await db().prepare("SELECT a.* FROM content_assets a JOIN content_courses c ON c.id=a.course_id WHERE a.id=? AND a.kind='image' AND a.status='ready' AND c.published IS NOT NULL AND c.status!='archive' AND EXISTS(SELECT 1 FROM json_each(c.published_assets) WHERE value=a.id)").bind(url.searchParams.get('id')).first<any>();if(!a)throw new InputError('Cover image not found.',404);const object=await bucket().get(a.storage_key);if(!object)throw new InputError('Cover image unavailable.',404);return fileResponse(object.body,a.mime,a.name,true);}
 if(action==='intro'){const config=JSON.parse((await db().prepare("SELECT data FROM site_content WHERE id='public'").first<any>())?.data??'{}');const {row,asset}=await validateIntroduction(config.introCourse??'');if(asset.storage_key&&asset.mime==='video/mp4')return json({provider:'storage',url:'/api/video-stream?intro=1&assetId='+asset.id});return json(await playback({userId:'public-introduction'},row.id,asset.id));}
 if(action==='sample-pdf'){const token=url.searchParams.get('token');if(token){const r=await db().prepare('SELECT expires_at FROM sample_requests WHERE token_hash=?').bind(await digest(token)).first<any>();if(!r||r.expires_at<Date.now())throw new InputError('This sample link expired. Request a fresh sample.',410);}else if(url.searchParams.get('preview')!=='1')throw new InputError('Request your free sample first.',403);const subject=url.searchParams.get('subject')??'physics';const p=(await catalog()).find(p=>p.subject===subject);if(!p)throw new InputError('Subject not found.',404);return fileResponse(await documentPdf([{title:p.title+' — sample',lines:['Educator review required. Digital resources only.',p.description,'Ask learners what they predict. Explore one variable and record what changes.','Activity planning time: '+p.minutes+' minutes. Suggested ages: '+p.ages]},{title:'Materials & observation sheet',lines:[...p.materials,'My prediction: __________________________','What happened: __________________________','What I would change: _____________________','Adults review hazards, supervise children and handle sharp tools and batteries.']}],'SwIRL public sample • Not approved curriculum'),'application/pdf','swirl-sample.pdf',url.searchParams.get('preview')==='1');}
 if(!['cms','cms/course','cms/storage-status','billing-readiness','classroom','asset','bundle','course-supplies','receipt','license-receipt','program','program-quote','certificate','marketing','notifications','inquiries'].includes(action))return null;
 const u=await user();
 if(action==='billing-readiness'){await content().admin(u);const config=settings(),last=await db().prepare('SELECT max(created_at) AS received FROM events').first<any>(),probe=await db().prepare("SELECT data FROM site_content WHERE id='stripe-check'").first<any>();let origin=false;try{const u=new URL(config.SITE_ORIGIN);origin=u.protocol==='https:'&&u.origin===config.SITE_ORIGIN}catch{}return json({checks:[{label:'Stripe test secret key',ready:config.STRIPE_SECRET_KEY?.startsWith('sk_test_')===true},{label:'Webhook signing secret',ready:!!config.STRIPE_WEBHOOK_SECRET},{label:'Secure billing return address',ready:origin},{label:'Signed webhook received',ready:!!last?.received}],lastWebhook:last?.received??null,connection:probe?JSON.parse(probe.data):null,videoReady:true,videoProvider:'Private MP4 storage',adaptiveVideoReady:!!(config.MUX_TOKEN_ID&&config.MUX_TOKEN_SECRET&&config.MUX_SIGNING_KEY_ID&&config.MUX_SIGNING_PRIVATE_KEY),emailReady:!!(config.RESEND_API_KEY&&config.EMAIL_FROM)});}
 if(action==='cms')return json(await content().list(u));
 if(action==='cms/storage-status')return json(await storedVideo().status(u,url.searchParams.get('id')));
 if(action==='cms/course')return json(await content().detail(u,url.searchParams.get('id')));
 if(action==='program')return json(await program().view(u));
 if(action==='inquiries'){await content().admin(u);const rows=(await db().prepare("SELECT id,data,created_at,'pilot/inquiry' AS source FROM leads UNION ALL SELECT id,data,created_at,'sample' AS source FROM sample_requests ORDER BY created_at DESC LIMIT 150").all<any>()).results;return json({items:await Promise.all(rows.map(async r=>({...r,data:JSON.parse(r.data),review:(await db().prepare("SELECT detail FROM audit_log WHERE action='inquiry-review' AND target=? ORDER BY created_at DESC LIMIT 1").bind(r.id).first<any>())?.detail??'New'})))});}
 if(action==='notifications'){await content().admin(u);return json({items:(await db().prepare('SELECT id,recipient,subject,status,created_at FROM email_outbox ORDER BY created_at DESC LIMIT 100').all()).results});}
 if(action==='program-quote'){const r=await program().requestRow(u,url.searchParams.get('id')),d=JSON.parse(r.data);return fileResponse(await documentPdf([{title:'SwIRL '+(d.kind==='po'?'purchase order request':'formal test quote'),lines:['Reference: '+r.id,'Issued: '+new Date(r.created_at).toISOString().slice(0,10),'Valid through: '+new Date(d.validUntil).toISOString().slice(0,10),'Prepared for: '+d.organization,d.name+' • '+d.email,'Scope: '+d.scope,'Physical sites: '+d.sites,'Annual unit price: USD '+(d.unitPrice/100).toFixed(2),'Subtotal: USD '+(r.amount/100).toFixed(2),'Tax: calculated on approved invoice if applicable.','PO: '+(d.po||'Not applicable'),'Status: '+r.status,d.terms,...(r.review_note?['Review: '+r.review_note]:[])]}],'SwIRL test billing • No real charge or approved production license'),'application/pdf',r.id+'.pdf');}
 if(action==='certificate'){const r=await program().requestRow(u,url.searchParams.get('id'));if(!r.certificate_key)throw new InputError('No certificate uploaded.',404);const object=await bucket().get(r.certificate_key);if(!object)throw new InputError('File unavailable.',404);return fileResponse(object.body,r.certificate_mime,'tax-certificate.pdf');}
 if(action==='marketing'){const title=textField(url.searchParams.get('title')??'Our STEM discovery week','Program title',120),organization=textField(url.searchParams.get('organization')??'Your school','Organization',160),details=textField(url.searchParams.get('details')??'Join us for hands-on science, engineering and discovery.','Details',1500),kind=url.searchParams.get('kind')??'flyer';if(!['flyer','newsletter','daycare','afterschool','camp'].includes(kind))throw new InputError('Choose a resource type.');return fileResponse(await documentPdf([{title:organization,lines:[title,details]},{title:kind==='newsletter'?'This month’s discoveries':'Hands-on learning, together',lines:kind==='daycare'?['Parent connection: Ask your child what changed during today’s activity.','Notice progress in describing observations, turn-taking and trying again.','These are observation prompts, not developmental assessments.']:kind==='afterschool'?['45–60 minute session: 5 min welcome, 10 min explore, 20–30 min build, 10 min test and reflect.','Before pickup: invite each learner to share one thing they changed.']:kind==='camp'?['Monday: questions and predictions','Tuesday: design and make','Wednesday: test one variable','Thursday: improve and prepare','Friday: family showcase — demonstrate discoveries and reflections']:['Learners ask, make, test and explain.','Digital curriculum; activity materials sourced by your program.','Contact your program organizer for dates, fees and registration.']}],'Prepared by '+(u.displayName||'an adult educator')+' • Customizable SwIRL template'),'application/pdf','swirl-'+kind+'.pdf');}
 const id=url.searchParams.get('id')??'',preview=url.searchParams.get('preview')==='1';
 if(action==='classroom'||action==='bundle'){const {row,data}=await coursePermission(u,id,preview),assets=await courseAssets(row,preview);if(action==='classroom')return json({data,assets:assets.map(a=>({id:a.id,kind:a.kind,lesson:a.lesson_index,language:a.language,name:a.name,status:a.status})),preview});const lang=url.searchParams.get('lang')??'en';if(!['en','es'].includes(lang))throw new InputError('Choose English or Spanish.');const docs=assets.filter(a=>['plan','worksheet','book'].includes(a.kind)&&a.language===lang);if(lang==='es'&&!docs.length)throw new InputError('Spanish documents have not been uploaded for this curriculum.',404);const chosen=Array.from(new Map(docs.map(a=>[a.kind+':'+a.lesson_index,a])).values());if(chosen.reduce((n,a)=>n+a.size,0)>20*1024*1024)throw new InputError('The bundle exceeds 20 MB. Download individual documents instead.',413);const buffers=[];for(const a of chosen){const file=await bucket().get(a.storage_key);if(!file)throw new InputError('A teaching document is temporarily unavailable.',503);buffers.push(new Uint8Array(await file.arrayBuffer()));}const generated=await documentPdf([{title:data.title,lines:[data.description,'Learning outcomes: '+data.outcomes,'Safety: '+data.safety,...(data.sample?['SAMPLE — educator review required']:[])]},...data.steps.map((s:any,i:number)=>({title:`${i+1}. ${s.title}`,lines:['Preparation: '+s.prep,s.instructions]})),{title:'Bill of materials',lines:data.materials}],'SwIRL teaching notes');await content().audit(u,'bundle-download',id,lang).run();return fileResponse(await bundlePdf(buffers,generated,'SwIRL • '+(u.displayName||u.userId)+' • '+new Date().toISOString().slice(0,10)),'application/pdf',id+'-'+lang+'.pdf',url.searchParams.get('inline')==='1');}
 if(action==='course-supplies'){const {data}=await coursePermission(u,id,preview);return fileResponse(['Item,Quantity note',...data.materials.map((m:string)=>csvCell(m)+',"Adjust for group size"')].join('\r\n'),'text/csv; charset=utf-8',id+'-supplies.csv');}
 if(action==='license-receipt'){const row=await db().prepare("SELECT l.*,s.name AS school_name FROM licenses l JOIN schools s ON s.id=l.school_id WHERE l.id=? AND s.owner_id=? AND l.status='paid'").bind(url.searchParams.get('id'),u.userId).first<any>();if(!row)throw new InputError('Receipt not found.',404);return fileResponse(await documentPdf([{title:'SwIRL test license receipt',lines:['License: '+row.id,'Location: '+(row.checkout_data?JSON.parse(row.checkout_data).schoolName:row.school_name),'Scope: '+row.scope,'Access starts: '+new Date(row.starts_at).toISOString().slice(0,10),'Access ends (exclusive): '+new Date(row.ends_at).toISOString().slice(0,10),'Base price: USD '+(row.amount/100).toFixed(2),row.paid_total!==null?'Verified test amount paid: USD '+(row.paid_total/100).toFixed(2):'Consult the Stripe invoice for the final payment total.',row.paid_at?'Confirmed: '+new Date(row.paid_at).toISOString().slice(0,10):'Payment confirmed before receipt tracking was added.','No real charge was made. This is not a tax invoice.']}]),'application/pdf','swirl-license-test-receipt.pdf');}
 if(action==='receipt'){const row=await db().prepare("SELECT * FROM orders WHERE id=? AND user_id=? AND status='complete'").bind(id,u.userId).first<any>();if(!row)throw new InputError('Receipt not found.',404);const snapshot=row.snapshot?JSON.parse(row.snapshot):null,lines=snapshot?.lines??JSON.parse(row.items).map((id:string)=>({title:id}));return fileResponse(await documentPdf([{title:row.mode==='demo'?'Sample order confirmation':'Stripe test payment receipt',lines:['Order: '+row.id,'Date: '+new Date(row.created_at).toISOString().slice(0,10),'Prepared for: '+(u.displayName||u.email),...lines.map((p:any)=>p.title+(p.price!==undefined?' - USD '+(p.price/100).toFixed(2):'')),'Subtotal: USD '+(row.total/100).toFixed(2),'Test amount paid: USD '+(row.mode==='demo'?0:((row.paid_total??row.total)/100)).toFixed(2),'No real charge was made. This is not a tax invoice.']}]),'application/pdf','swirl-test-receipt.pdf');}
 if(action==='asset'){const a=await db().prepare('SELECT * FROM content_assets WHERE id=?').bind(id).first<any>();if(!a)throw new InputError('File not found.',404);const {row}=await coursePermission(u,a.course_id,preview);if(!(await courseAssets(row,preview)).some(item=>item.id===id)||!a.storage_key)throw new InputError('File is not part of this curriculum version.',404);if(['video','prep','preview'].includes(a.kind))throw new InputError('Open this video in the lesson player.',400);const object=await bucket().get(a.storage_key);if(!object)throw new InputError('File unavailable.',404);await content().audit(u,'asset-download',a.course_id,a.kind).run();if(a.mime==='application/pdf'){const bytes=await bundlePdf([new Uint8Array(await object.arrayBuffer())],null,'SwIRL • '+(u.displayName||u.userId));return fileResponse(bytes,a.mime,a.name,url.searchParams.get('inline')==='1');}if(a.mime==='text/csv')return fileResponse(sanitizeCsv(await object.text()),'text/csv; charset=utf-8',a.name);return fileResponse(object.body,a.mime,a.name,a.kind==='image'||a.kind==='captions');}
 return null;
}
export async function featurePost(req:Request):Promise<Response|null>{const url=new URL(req.url),action=url.pathname.slice(5);if(!action.startsWith('cms/')&&!action.startsWith('program/')&&!['sample-request','certificate-upload','notify-retry','site-config'].includes(action))return null;const rawBytes=await boundedBytes(req,action==='cms/storage-part'?8*1024*1024:action==='cms/upload'?25*1024*1024:action==='certificate-upload'?10*1024*1024:action==='cms/brand-upload'?5*1024*1024:400000);assertSameOrigin(req);
 if(action==='sample-request'){const b=await body(req,new TextDecoder().decode(rawBytes));if(!['biology','physics','electronics','robotics','coding'].includes(b.subject))throw new InputError('Choose a STEM subject.');const lead=validateLead({...b,kind:'pilot',sites:1}),ip=req.headers.get('cf-connecting-ip')??'local',ipHash=await digest(ip+':'+Math.floor(Date.now()/86400000));const n=await db().prepare('SELECT count(*) AS n FROM sample_requests WHERE ip_hash=? AND created_at>?').bind(ipHash,Date.now()-3600000).first<any>();if(n.n>=5)throw new InputError('Please wait an hour before requesting another sample.',429);const token=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),id=crypto.randomUUID();await db().prepare('INSERT INTO sample_requests(id,token_hash,ip_hash,data,created_at,expires_at) VALUES(?,?,?,?,?,?)').bind(id,await digest(token),ipHash,JSON.stringify(lead),Date.now(),Date.now()+86400000).run();return json({url:'/api/sample-pdf?token='+token+'&subject='+encodeURIComponent(b.subject??'physics'),video:sampleSource,message:'Your sample is ready. This link is valid for 24 hours.'});}
 const u=await user();
 if(action==='cms/storage-part')return json(await storedVideo().part(u,url.searchParams.get('id'),Number(url.searchParams.get('part')),rawBytes));
 if(action==='cms/brand-upload'){await content().admin(u);if(url.searchParams.get('approved')!=='true')throw new InputError('Verify permission to display this partner logo.');const name=textField(url.searchParams.get('partner'),'Partner name',100),filename=textField(url.searchParams.get('name'),'File name',180),bytes=rawBytes,mime=await validateFile(bytes,filename,req.headers.get('content-type'),'image'),id='logo-'+(await digest(name+await digest(bytes))).slice(0,32),key='branding/'+id;if((await db().prepare("SELECT count(*) AS n FROM content_assets WHERE kind='partner-logo' AND status='ready'").first<any>()).n>=20)throw new InputError('Keep at most 20 active partner logos.',429);await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});await db().prepare("INSERT INTO content_assets(id,course_id,owner_id,kind,lesson_index,language,name,mime,size,storage_key,status,created_at) VALUES(?,'site-branding',?,'partner-logo',0,'en',?,?,?,?,'ready',?) ON CONFLICT(id) DO UPDATE SET status='ready'").bind(id,u.userId,name,mime,bytes.length,key,Date.now()).run();return json({saved:true});}
 if(action==='cms/upload'){const b={courseId:url.searchParams.get('courseId'),kind:url.searchParams.get('kind'),language:url.searchParams.get('language'),lesson:Number(url.searchParams.get('lesson')),name:url.searchParams.get('name')};const m=await content().assetMeta(u,b),bytes=rawBytes,mime=await validateFile(bytes,m.name,req.headers.get('content-type')?.split(';')[0],m.kind),id='asset-'+(await digest(u.userId+JSON.stringify(b)+await digest(bytes))).slice(0,40),key='curriculum/'+m.courseId+'/'+id;const count=await db().prepare("SELECT count(*) AS n FROM content_assets WHERE course_id=? AND status!='deleted'").bind(m.courseId).first<any>();if(count.n>=150&&!await db().prepare('SELECT id FROM content_assets WHERE id=?').bind(id).first())throw new InputError('This course has reached its file limit.',429);await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});await content().attachAsset(u,m,{id,mime,size:bytes.length,key,status:'ready'});return json({id,status:'ready'});}
 if(action==='certificate-upload'){const id=url.searchParams.get('id'),r=await program().requestRow(u,id);if(r.user_id!==u.userId||r.status!=='submitted')throw new InputError('Certificates can be uploaded only by the requester before approval.',403);const bytes=rawBytes;await validateFile(bytes,'certificate.pdf',req.headers.get('content-type'),'certificate');const key='certificates/'+r.id+'/'+await digest(bytes);await bucket().put(key,bytes,{httpMetadata:{contentType:'application/pdf'}});const result=await db().prepare("UPDATE purchase_requests SET certificate_key=?,certificate_mime='application/pdf' WHERE id=? AND status='submitted'").bind(key,r.id).run();if(!result.meta.changes)throw new InputError('The request was reviewed during upload. Reload its status.',409);return json({saved:true});}
 const raw=new TextDecoder().decode(rawBytes);if(raw.length>400000)throw new InputError('The lesson is too large.',413);if(!req.headers.get('content-type')?.includes('application/json'))throw new InputError('Send JSON.',415);let b:any;try{b=JSON.parse(raw)}catch{throw new InputError('Invalid form data.')}if(!b||typeof b!=='object'||Array.isArray(b))throw new InputError('Invalid form data.');
 if(action==='cms/storage-start')return json(await storedVideo().start(u,b));
 if(action==='cms/storage-complete')return json(await storedVideo().complete(u,b.id));
 if(action==='cms/storage-cancel')return json(await storedVideo().cancel(u,b.id));
 if(action==='cms/stripe-check'){await content().admin(u);const balance=await stripe('balance');if(balance.livemode!==false)throw new InputError('Only a Stripe sandbox connection is accepted.',409);const result={connected:true,mode:'test',checkedAt:Date.now()};await db().prepare("INSERT INTO site_content(id,data,updated_at) VALUES('stripe-check',?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at").bind(JSON.stringify(result),Date.now()).run();return json(result);}
 if(action==='cms/inquiry-review'){await content().admin(u);const note=textField(b.note,'Review note',1000);await content().audit(u,'inquiry-review',String(b.id??''),note).run();return json({saved:true});}
 if(action==='cms/brand-remove'){await content().admin(u);await db().prepare("UPDATE content_assets SET status='deleted' WHERE id=? AND kind='partner-logo'").bind(String(b.id??'')).run();return json({removed:true});}
 if(action==='cms/request')return json(await content().request(u));
 if(action==='cms/grant')return json(await content().grant(u,b.userId,b.role));
 if(action==='cms/create')return json(await content().create(u,b.key));
 if(action==='cms/save')return json(await content().save(u,b.id,b.revision,b.data));
 if(action==='cms/status')return json(await content().transition(u,b.id,b.revision,b.action));
 if(action==='cms/remove-asset'||action==='cms/video-cancel')return json(await removeVideo(u,b.id));
 if(action==='cms/youtube-link')return json(await linkYoutube({db:db(),content:content()},u,b));
 if(action==='cms/video-start')return json(await startVideo(u,b));
 if(action==='cms/video-sync')return json(await syncVideo(u,b.id));
 if(action==='cms/play')return json(await playback(u,b.id,b.assetId,b.preview===true));
 if(action==='program/seasonal')return json(await program().seasonal(u,b));
 if(action==='program/confirm')return json(await program().confirm(u,b.sessionId));
 if(action==='program/submit')return json(await program().submit(u,b));
 if(action==='program/review')return json(await program().review(u,b));
 if(action==='program/refresh')return json(await program().refresh(u,b.id));
 if(action==='notify-retry'){await content().admin(u);return json(await mail().deliver(b.id));}
 if(action==='site-config'){await content().admin(u);const data={introCourse:textField(b.introCourse??'','Introduction course ID',80,false),partners:textField(b.partners??'','Approved partners',1500,false),impact:textField(b.impact??'','Verified impact statement',500,false),impactCount:Number(b.impactCount??0),impactLabel:textField(b.impactLabel??'','Impact counter label',100,false)};if(data.introCourse)await validateIntroduction(data.introCourse);if(!Number.isInteger(data.impactCount)||data.impactCount<0||data.impactCount>100000000)throw new InputError('Enter a valid verified impact count.');if((data.partners||data.impact||data.impactCount)&&b.approved!==true)throw new InputError('Confirm that partner permissions and impact statements have been verified.');await db().prepare("INSERT INTO site_content(id,data,updated_at) VALUES('public',?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at").bind(JSON.stringify(data),Date.now()).run();return json({saved:true});}
 throw new InputError('Not found.',404);
}
