import {db,settings} from './server';
import {content,coursePermission,courseAssets} from './content-server';
import {InputError} from './core.mjs';
import {siteOrigin} from './school-billing.mjs';
async function mux(path:string,data?:unknown,method?:string){const s=settings();if(!s.MUX_TOKEN_ID||!s.MUX_TOKEN_SECRET)throw new InputError('Video uploads need the site owner’s Mux connection. PDF and lesson editing are available now.',503);const r=await fetch('https://api.mux.com/video/v1/'+path,{method:method??(data?'POST':'GET'),headers:{Authorization:'Basic '+btoa(s.MUX_TOKEN_ID+':'+s.MUX_TOKEN_SECRET),'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(20000)});if(!r.ok)throw new InputError('The video provider could not complete this request. Try again shortly.',502);if(r.status===204)return {};return ((await r.json()) as any).data;}
export async function startVideo(u:any,b:any){const m=await content().assetMeta(u,b);if(!['video','prep','preview'].includes(m.kind))throw new InputError('Choose a video purpose.');const count=await db().prepare("SELECT count(*) AS n FROM content_assets WHERE owner_id=? AND provider_id IS NOT NULL AND created_at>?").bind(u.userId,Date.now()-86400000).first<any>();if(count.n>=20)throw new InputError('Daily video upload limit reached.',429);const upload=await mux('uploads',{timeout:3600,cors_origin:siteOrigin(settings()),new_asset_settings:{playback_policies:['signed'],video_quality:'basic',passthrough:m.id,inputs:[{generated_subtitles:[{language_code:m.language,name:m.language==='es'?'Spanish CC':'English CC'}]}]}});if(!upload.id||!upload.url)throw new InputError('The video provider did not return an upload URL.',502);try{await content().attachAsset(u,m,{id:m.id,mime:'video/mp4',size:0,providerId:upload.id,status:'uploading'});}catch(e){await mux('uploads/'+encodeURIComponent(upload.id)+'/cancel',undefined,'PUT').catch(()=>{});throw e;}return {id:m.id,url:upload.url};}
export async function syncVideo(u:any,id:string){const a=await content().asset(u,id);if(!a.provider_id)throw new InputError('This file is not a video.');const upload=await mux('uploads/'+encodeURIComponent(a.provider_id));let status=upload.status==='asset_created'?'processing':upload.status;if(upload.asset_id){const asset=await mux('assets/'+encodeURIComponent(upload.asset_id));if(asset.passthrough!==a.id)throw new InputError('Video ownership verification failed.',409);const playback=asset.playback_ids?.find((p:any)=>p.policy==='signed');status=asset.status==='ready'&&playback?'ready':asset.status;if(asset.duration>7200)status='too_long';await content().updateVideo(u,a.id,a.status,status,status==='ready'?playback.id:null);return {status,captions:asset.tracks?.filter((t:any)=>t.type==='text').map((t:any)=>({language:t.language_code,status:t.status}))??[]};}await content().updateVideo(u,a.id,a.status,status,null);return {status};}
const bytes=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const b64=(b:Uint8Array)=>btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
function der(tag:number,data:Uint8Array){let n=data.length;const length:number[]=[];while(n){length.unshift(n&255);n>>>=8}return new Uint8Array([tag,...(data.length<128?[data.length]:[128+length.length,...length]),...data]);}
async function token(id:string,seconds:number){const s=settings();if(!s.MUX_SIGNING_KEY_ID||!s.MUX_SIGNING_PRIVATE_KEY)throw new InputError('Secure video playback needs a Mux signing key.',503);let pem=s.MUX_SIGNING_PRIVATE_KEY;if(!pem.includes('BEGIN'))pem=atob(pem);let keyBytes=bytes(pem.replace(/-----[^-]+-----/g,'').replace(/\s/g,''));if(pem.includes('BEGIN RSA PRIVATE KEY'))keyBytes=der(48,new Uint8Array([2,1,0,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,...der(4,keyBytes)]));let key;try{key=await crypto.subtle.importKey('pkcs8',keyBytes as BufferSource,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign'])}catch{throw new InputError('The Mux signing key format needs attention.',503)}const encode=(o:any)=>b64(new TextEncoder().encode(JSON.stringify(o))),jwt=encode({alg:'RS256',typ:'JWT',kid:s.MUX_SIGNING_KEY_ID})+'.'+encode({sub:id,aud:'v',exp:Math.floor(Date.now()/1000)+seconds,kid:s.MUX_SIGNING_KEY_ID});return jwt+'.'+b64(new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(jwt))));}
export async function playback(u:any,id:string,assetId:string,preview=false){const {row}=await coursePermission(u,id,preview),a=(await courseAssets(row,preview)).find(a=>a.id===assetId&&a.playback_id);if(!a)throw new InputError('Processed video not found.',404);const jwt=await token(a.playback_id,10800);await content().audit(u,'video-play',id,a.kind).run();return {url:`https://stream.mux.com/${a.playback_id}.m3u8?token=${jwt}`,expiresAt:Date.now()+10800000};}

export async function removeVideo(u:any,id:string){const a=await content().asset(u,id);await content().remove(u,id);if(!a.provider_id)return {removed:true};try{const upload=await mux('uploads/'+encodeURIComponent(a.provider_id));if(upload.status==='waiting')await mux('uploads/'+encodeURIComponent(a.provider_id)+'/cancel',undefined,'PUT');else if(upload.asset_id){const asset=await mux('assets/'+encodeURIComponent(upload.asset_id));if(asset.passthrough!==a.id)throw new InputError('Video ownership verification failed.',409);await mux('assets/'+encodeURIComponent(upload.asset_id),undefined,'DELETE');}return {removed:true,providerCleaned:true};}catch{await content().audit(u,'video-cleanup-pending',a.id,'Remove unpublished provider asset from Mux dashboard.').run();return {removed:true,providerCleanupPending:true};}}
