import {InputError} from './core.mjs';
// Inspect the front-loaded movie metadata without buffering the movie itself.
export function inspectMp4(bytes,totalSize=bytes.length){
 const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),type=i=>String.fromCharCode(...bytes.subarray(i,i+4)),invalid=()=>{throw new InputError('Invalid or incomplete MP4 metadata. Export H.264 MP4 with Fast Start / Web Optimized enabled.');};
 function boxes(start,end,partial=false){const out=[];let i=start;while(i<end){if(i+8>end){if(partial)break;invalid();}let size=v.getUint32(i),head=8;if(size===1){if(i+16>end)invalid();size=Number(v.getBigUint64(i+8));head=16;}if(size===0)size=(partial?totalSize:end)-i;if(!Number.isSafeInteger(size)||size<head||i+size>(partial?totalSize:end))invalid();const kind=type(i+4);if(i+size>end&&(!partial||kind!=='mdat'))invalid();out.push({type:kind,start:i+head,end:i+size});i+=size;if(out.length>10000)throw new InputError('MP4 metadata is too complex.');}return out;}
 const top=boxes(0,bytes.length,true),ftyp=top[0];if(ftyp?.type!=='ftyp'||ftyp.end-ftyp.start<8||(ftyp.end-ftyp.start)%4)invalid();const brands=[type(ftyp.start)];for(let i=ftyp.start+8;i<ftyp.end;i+=4)brands.push(type(i));if(!brands.some(b=>['isom','iso2','mp41','mp42','avc1'].includes(b)))invalid();const moov=top.find(b=>b.type==='moov'),mdat=top.find(b=>b.type==='mdat');if(!moov||!mdat||mdat.start<moov.end||mdat.end-mdat.start<16)invalid();
 const children=boxes(moov.start,moov.end),mvhd=children.find(b=>b.type==='mvhd');if(!mvhd||mvhd.end-mvhd.start<24)throw new InputError('MP4 duration metadata is missing.');const version=bytes[mvhd.start];if(version>1)throw new InputError('Unsupported MP4 metadata.');const offset=mvhd.start+(version===1?20:12);if(offset+(version===1?12:8)>mvhd.end)throw new InputError('Invalid MP4 duration.');const scale=v.getUint32(offset),ticks=version===1?Number(v.getBigUint64(offset+4)):v.getUint32(offset+4),duration=ticks/scale;if(!Number.isFinite(duration)||duration<=0||duration>7200)throw new InputError('MP4 videos must be longer than zero and no longer than two hours.');
 const codecs=[];for(const track of children.filter(b=>b.type==='trak')){let levels=[track];for(const name of ['mdia','minf','stbl'])levels=levels.flatMap(b=>boxes(b.start,b.end).filter(x=>x.type===name));for(const b of levels){const stsd=boxes(b.start,b.end).find(x=>x.type==='stsd');if(!stsd||stsd.end-stsd.start<8)invalid();const entries=boxes(stsd.start+8,stsd.end);if(!entries.length||v.getUint32(stsd.start+4)!==entries.length)invalid();for(const entry of entries){codecs.push(entry.type);if(['avc1','avc3'].includes(entry.type)){if(entry.end-entry.start<78||!v.getUint16(entry.start+24)||!v.getUint16(entry.start+26))invalid();const config=boxes(entry.start+78,entry.end).find(x=>x.type==='avcC');if(!config||config.end-config.start<8||bytes[config.start]!==1)invalid();let pos=config.start+6;const sps=bytes[config.start+5]&31;if(!sps)invalid();for(let n=0;n<sps;n++){if(pos+2>config.end)invalid();const length=v.getUint16(pos);pos+=2;if(!length||pos+length>config.end)invalid();pos+=length;}if(pos>=config.end)invalid();const pps=bytes[pos++];if(!pps)invalid();for(let n=0;n<pps;n++){if(pos+2>config.end)invalid();const length=v.getUint16(pos);pos+=2;if(!length||pos+length>config.end)invalid();pos+=length;}}else if(entry.type==='mp4a'&&entry.end-entry.start<28)invalid();}}}
 if(!codecs.some(c=>['avc1','avc3'].includes(c))||codecs.some(c=>!['avc1','avc3','mp4a','wvtt','stpp'].includes(c)))throw new InputError('Export H.264 MP4 video with AAC audio for browser compatibility.');return {duration,codecs};
}
export function videoRange(header,size){
 if(!header)return null;const m=/^bytes=(\d*)-(\d*)$/.exec(header);if(!m||(!m[1]&&!m[2]))throw new InputError('Unsupported byte range.',416);let start,end;if(!m[1]){const suffix=Number(m[2]);if(!Number.isSafeInteger(suffix)||suffix<=0)throw new InputError('Invalid byte range.',416);start=Math.max(0,size-suffix);end=size-1;}else{start=Number(m[1]);end=m[2]?Math.min(Number(m[2]),size-1):size-1;}if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||start>=size||end<start)throw new InputError('Byte range unavailable.',416);return {offset:start,length:end-start+1};
}
