import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {InputError,assertTestKey,isPayableSession} from './core.mjs';
import {findProduct} from './catalog';
export function db(){if(!env.DB)throw new InputError('Your classroom is temporarily unavailable. Please try again shortly.',503);return env.DB;}
export function settings(){return env as unknown as Record<string,string>}
export async function user(){const u=await getChatGPTUser();if(!u)throw new InputError('Sign in to continue.',401);return u;}
export function json(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
export async function body(req:Request,rawInput?:string){if(!req.headers.get('content-type')?.includes('application/json'))throw new InputError('Send JSON data.',415);const raw=rawInput??await req.text();if(raw.length>16000)throw new InputError('The request is too large.',413);let parsed;try{parsed=JSON.parse(raw)}catch{throw new InputError('The request could not be read.');}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new InputError('Expected a JSON object.');return parsed;}
export function failure(e:unknown){if(e instanceof InputError)return json({error:e.message},e.status);console.error('Request failed',e instanceof Error?e.message:'Unknown error');return json({error:'Something went wrong. Your request was not confirmed. Please try again.'},503);}
export async function stripe(path:string,form?:URLSearchParams,key?:string){const secret=settings().STRIPE_SECRET_KEY;assertTestKey(secret);const response=await fetch('https://api.stripe.com/v1/'+path,{method:form?'POST':'GET',headers:{Authorization:'Bearer '+secret,...(form?{'Content-Type':'application/x-www-form-urlencoded'}:{}),...(key?{'Idempotency-Key':key}:{})},body:form?.toString(),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new InputError('Stripe test checkout is unavailable. Please try again. No access has been granted.',502);return response.json() as Promise<any>;}
export async function fulfill(sessionId:string){const order=await db().prepare('SELECT * FROM orders WHERE session_id = ?').bind(sessionId).first<any>();if(!order)throw new InputError('Order is not available yet. Please retry.',409);const session=await stripe('checkout/sessions/'+encodeURIComponent(sessionId));if(!isPayableSession(session,order))return {status:'pending'};const ids:string[]=JSON.parse(order.items),now=Date.now();await db().batch([...ids.map(id=>db().prepare('INSERT INTO entitlements (user_id,product_id,order_id,mode,created_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id,product_id) DO NOTHING').bind(order.user_id,id,order.id,'stripe-test',now)),db().prepare("UPDATE orders SET status = 'complete' WHERE id = ?").bind(order.id),db().prepare("UPDATE carts SET items = (SELECT coalesce(json_group_array(value),'[]') FROM json_each(carts.items) WHERE value NOT IN (SELECT product_id FROM entitlements WHERE user_id = ?)), updated_at = ? WHERE user_id = ?").bind(order.user_id,now,order.user_id)]);return {status:'complete'};}
export async function requireAccess(userId:string,id:string){if(!findProduct(id))throw new InputError('Curriculum not found.',404);const entitlement=await db().prepare('SELECT * FROM entitlements WHERE user_id = ? AND product_id = ?').bind(userId,id).first<any>();if(!entitlement)throw new InputError('Add this resource to your classroom before opening it.',403);return entitlement;}
