// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import {sqliteTable,text,integer,primaryKey,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const carts=sqliteTable('carts',{userId:text('user_id').primaryKey(),items:text('items').notNull(),updatedAt:integer('updated_at').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),userId:text('user_id').notNull(),items:text('items').notNull(),total:integer('total').notNull(),status:text('status').notNull(),mode:text('mode').notNull(),sessionId:text('session_id'),snapshot:text('snapshot'),paidTotal:integer('paid_total'),invoiceUrl:text('invoice_url'),invoicePdf:text('invoice_pdf'),createdAt:integer('created_at').notNull()},t=>[index('orders_user').on(t.userId)]);
export const entitlements=sqliteTable('entitlements',{userId:text('user_id').notNull(),productId:text('product_id').notNull(),orderId:text('order_id').notNull(),mode:text('mode').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.userId,t.productId]})]);
export const leads=sqliteTable('leads',{id:text('id').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull(),createdAt:integer('created_at').notNull()},t=>[index('leads_user').on(t.userId)]);
export const progress=sqliteTable('progress',{userId:text('user_id').notNull(),productId:text('product_id').notNull(),completed:text('completed').notNull()},t=>[primaryKey({columns:[t.userId,t.productId]})]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),createdAt:integer('created_at').notNull()});
export const schools=sqliteTable('schools',{
 id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),name:text('name').notNull(),createdAt:integer('created_at').notNull(),
 customerId:text('customer_id'),subscriptionId:text('subscription_id'),status:text('status').notNull().default('none'),
 paidUntil:integer('paid_until').notNull().default(0),periodEnd:integer('period_end').notNull().default(0),
 cancelAtEnd:integer('cancel_at_end').notNull().default(0),syncedAt:integer('synced_at').notNull().default(0)
},t=>[index('schools_owner').on(t.ownerId),uniqueIndex('schools_owner_name').on(t.ownerId,t.name),uniqueIndex('schools_customer').on(t.customerId),uniqueIndex('schools_subscription').on(t.subscriptionId)]);
export const schoolMembers=sqliteTable('school_members',{schoolId:text('school_id').notNull().references(()=>schools.id),userId:text('user_id').notNull(),name:text('name').notNull(),joinedAt:integer('joined_at').notNull()},t=>[primaryKey({columns:[t.schoolId,t.userId]}),index('school_members_user').on(t.userId)]);
export const schoolInvites=sqliteTable('school_invites',{id:text('id').primaryKey(),schoolId:text('school_id').notNull().references(()=>schools.id),tokenHash:text('token_hash').notNull(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),acceptedBy:text('accepted_by'),revoked:integer('revoked').notNull().default(0)},t=>[uniqueIndex('school_invites_hash').on(t.tokenHash),index('school_invites_school').on(t.schoolId)]);
export const schoolCheckouts=sqliteTable('school_checkouts',{schoolId:text('school_id').primaryKey().references(()=>schools.id),attempt:text('attempt').notNull(),sessionId:text('session_id'),createdAt:integer('created_at').notNull()});
export const schoolLocks=sqliteTable('school_locks',{schoolId:text('school_id').primaryKey().references(()=>schools.id),token:text('token').notNull(),expiresAt:integer('expires_at').notNull()});
export const contentUsers=sqliteTable('content_users',{userId:text('user_id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),role:text('role').notNull(),createdAt:integer('created_at').notNull()});
export const contentCourses=sqliteTable('content_courses',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),draft:text('draft').notNull(),published:text('published'),publishedAssets:text('published_assets'),status:text('status').notNull(),revision:integer('revision').notNull(),publishedRevision:integer('published_revision'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()});
export const contentAssets=sqliteTable('content_assets',{id:text('id').primaryKey(),courseId:text('course_id').notNull(),ownerId:text('owner_id').notNull(),kind:text('kind').notNull(),lessonIndex:integer('lesson_index').notNull(),language:text('language').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),storageKey:text('storage_key'),providerId:text('provider_id'),playbackId:text('playback_id'),status:text('status').notNull(),createdAt:integer('created_at').notNull()},t=>[index('assets_course').on(t.courseId)]);
export const auditLog=sqliteTable('audit_log',{id:text('id').primaryKey(),userId:text('user_id').notNull(),action:text('action').notNull(),target:text('target').notNull(),detail:text('detail').notNull(),createdAt:integer('created_at').notNull()});
export const sampleRequests=sqliteTable('sample_requests',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull(),ipHash:text('ip_hash').notNull(),data:text('data').notNull(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull()});
export const emailOutbox=sqliteTable('email_outbox',{id:text('id').primaryKey(),userId:text('user_id').notNull(),recipient:text('recipient').notNull(),subject:text('subject').notNull(),message:text('message').notNull(),status:text('status').notNull(),providerId:text('provider_id'),createdAt:integer('created_at').notNull()});
export const licenses=sqliteTable('licenses',{id:text('id').primaryKey(),schoolId:text('school_id').notNull(),userId:text('user_id').notNull(),scope:text('scope').notNull(),startsAt:integer('starts_at').notNull(),endsAt:integer('ends_at').notNull(),amount:integer('amount').notNull(),status:text('status').notNull(),sessionId:text('session_id'),createdAt:integer('created_at').notNull()});
export const purchaseRequests=sqliteTable('purchase_requests',{id:text('id').primaryKey(),userId:text('user_id').notNull(),schoolId:text('school_id').notNull(),data:text('data').notNull(),amount:integer('amount').notNull(),status:text('status').notNull(),certificateKey:text('certificate_key'),certificateMime:text('certificate_mime'),customerId:text('customer_id'),invoiceId:text('invoice_id'),invoiceUrl:text('invoice_url'),invoicePdf:text('invoice_pdf'),reviewNote:text('review_note'),createdAt:integer('created_at').notNull(),approvedAt:integer('approved_at')});
export const billingLocks=sqliteTable('billing_locks',{id:text('id').primaryKey(),token:text('token').notNull(),expiresAt:integer('expires_at').notNull()});
export const siteContent=sqliteTable('site_content',{id:text('id').primaryKey(),data:text('data').notNull(),updatedAt:integer('updated_at').notNull()});
